// generated by rustscript-differential, seed 700697

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for usize {
    fn diff_describe(&self) -> String {
        format!("usize={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_char(value: char) -> char {
    value
}

fn main() {
    let v_0_7 = diff_opaque_char('9');
    let diff_cl_0_8 = |diff_p_0_9: String, diff_p_0_10: usize| -> String { String::from("") };
    println!("diff_cl_0_8_0: {:?}", ({ let mut diff_m = std::collections::BTreeMap::new(); for diff_x in vec![Some(v_0_7), Some(v_0_7)] { diff_m.entry(diff_x).and_modify(|n| *n += 2).or_insert(1usize); } format!("{:?} {:?}", diff_m.first_key_value(), diff_m.last_key_value()) }));
    {
        if let Some(diff_b_0_33) = None::<f32> {
            println!("lang_0_35: {:^9?}", (diff_opaque_u64(0) as u64));
            let v_0_36: i8 = (diff_opaque_i64(2) as i8);
        } else {
            println!("lang_0_37: {0:0} {0:?}", (&("")[1usize..2usize]));
        }
    }
}
