// generated by rustscript-differential, seed 20705100031

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u64 {
    fn diff_describe(&self) -> String {
        format!("u64={:?}", self)
    }
}

fn diff_opaque_true() -> bool {
    true
}

fn diff_pick_0<T: Clone + std::fmt::Debug>(a: T, b: T, first: bool) -> T {
    if first { a } else { b }
}

fn main() {
    let v_0_0 = diff_pick_0(
        Vec::<Option<f32>>::new(),
        Vec::<Option<f32>>::new(),
        (vec![DiffTrace(1), DiffTrace(2), DiffTrace(3)]
            .into_iter()
            .any(|diff_ref| {
                let diff_x_0_1: DiffTrace = diff_ref.clone();
                diff_opaque_true()
            })),
    );
}
