// generated by rustscript-differential, seed 77101942

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u64 {
    fn diff_describe(&self) -> String {
        format!("u64={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    println!("lang_0_104: {:?}", ({ let mut sorted = (vec![(diff_opaque_i64(1) as i8); 3usize].into_iter().map(|diff_x_0_103: i8| (diff_opaque_u64(0) as u16)).collect::<Vec<u16>>()); sorted.sort(); sorted.binary_search(&(diff_opaque_u64(0) as u16)) }));
}
