// generated by rustscript-differential, seed 701071

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn main() {
    let v_0_11 = ({ let mut diff_r = ({ let mut diff_it = Vec::<DiffTrace>::new().into_iter(); diff_it.next(); diff_it.next() }); let diff_d = DiffTrace(6); diff_r.get_or_insert(diff_d).clone() });
}
