// generated by rustscript-differential, seed 500118

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffS0_0 {
    f0: Vec<i32>,
    f1: DiffTrace,
}

impl DiffS0_0 {
    fn diff_m0(&self, diff_a_0_0: u16) -> Self {
        DiffS0_0 { f0: self.f0.clone(), ..Default::default() }
    }
    fn diff_new(diff_a_0_1: Vec<i32>, diff_a_0_2: DiffTrace) -> Self {
        DiffS0_0 { f0: diff_a_0_1, f1: diff_a_0_2 }
    }
}

fn main() {
    let mut v_0_3: f64 = diff_opaque_f64(0.0f64);
    let v_0_8: DiffTrace = DiffTrace(0);
    for diff_e_0_13 in (vec![Vec::<char>::new(); 1usize]).iter() {
        for diff_e_0_14 in (({ let diff_s = Vec::<Vec<DiffS0_0>>::new().into_iter().collect::<std::collections::BTreeSet<Vec<DiffS0_0>>>(); let diff_d = vec![DiffS0_0 { f0: Vec::<i32>::new(), f1: v_0_8.clone() }, DiffS0_0 { f0: vec![(diff_opaque_i64(0) as i32)], f1: v_0_8.clone() }]; diff_s.range(diff_d..).rev().cloned().collect::<Vec<Vec<DiffS0_0>>>() }).concat()).iter() {
            v_0_3 = diff_opaque_f64(0.0f64);
            for (diff_i_0_16, diff_e_0_15) in (*diff_e_0_13).iter().enumerate() {
                v_0_3 += diff_opaque_f64(0.0f64);
            }
        }
    }
}
