// generated by rustscript-differential, seed 77102811

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<f32> {
    fn diff_describe(&self) -> String {
        format!("Vec[f32]={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn main() {
    println!("lang_0_29: {:?}", ({ let mut diff_it = vec![(diff_opaque_i64(0) as i64), (diff_opaque_i64(-9223372036854775808) as i64)].into_iter(); let diff_head = diff_it.by_ref().take(1).collect::<Vec<i64>>(); (diff_head, diff_it.collect::<Vec<i64>>()) }));
}
