// generated by rustscript-differential, seed 20709206578

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_fn_0_24(diff_p_0_25_ref: &DiffTrace) -> (u64,) {
    let diff_p_0_25: DiffTrace = diff_p_0_25_ref.clone();
    ((diff_opaque_u64(0) as u64),)
}

fn main() {
    let mut v_0_0: DiffTrace = DiffTrace(1);
    let v_0_11 = v_0_0;
    v_0_0 = DiffTrace(0);
    println!("lang_0_19: {:?}", v_0_0);
    println!("lang_0_28: {0:?} {0:?}", diff_fn_0_24(&(((-5i64..-5i64).map(|diff_x_0_27| v_0_0.clone()).max()).unwrap_or_default())));
}
