// generated by rustscript-differential, seed 20707114533

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn main() {
    let mut v_0_5 = DiffTrace(0);
    v_0_5 = v_0_5;
    println!("lang_0_30: {:?}", (Vec::<(u32, i64)>::new().into_iter().map(|diff_x_0_29| v_0_5.clone()).nth(0usize)));
}
