// generated by rustscript-differential, seed 5259

use std::collections::HashMap;

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
struct DiffS0_0 {
    f0: usize,
    f1: i32,
}

impl std::fmt::Display for DiffS0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.pad(&format!("DiffS0_0 f0={:5?} f1={:?}", self.f0, self.f1))
    }
}

impl DiffS0_0 {
    fn diff_m0(&self, diff_a_0_0: char) -> Self {
        HashMap::<u64, Option<DiffS0_0>>::new().get(&(diff_opaque_u64(14546840635408624956) as u64)).cloned().unwrap_or(None::<DiffS0_0>).unwrap_or_default()
    }
    fn diff_new(diff_a_0_1: usize, diff_a_0_2: i32) -> Self {
        DiffS0_0 { f0: diff_a_0_1, f1: diff_a_0_2 }
    }
}

fn main() {
    let v_0_25: DiffS0_0 = (DiffS0_0 { f0: (diff_opaque_u64(0) as usize), f1: (diff_opaque_i64(0) as i32) }).diff_m0('_');
    println!("lang_0_36: {0:1$?}", (match (v_0_25.clone()) { DiffS0_0 { f0: diff_b_0_28, f1: diff_b_0_29, .. } => (diff_opaque_i64(0) as i16), }), 5usize);
    for _ in 0usize..1usize {
        println!("lang_0_40: {:-<.2E}", diff_opaque_f32(0.0f32).clamp(diff_opaque_f32(0.0f32), (((diff_opaque_i64(2147483646) as i32) as f32) - diff_opaque_f32(f32::MAX))));
    }
}
