// generated by rustscript-differential, seed 20708100103

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn main() {
    let mut v_0_4: Vec<DiffTrace> = vec![DiffTrace(1)];
    {
        v_0_4.clear();
    }
}
