// generated by rustscript-differential, seed 900023

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<u8> {
    fn diff_describe(&self) -> String {
        format!("Vec[u8]={:?}", self)
    }
}

impl DiffDescribe for char {
    fn diff_describe(&self) -> String {
        format!("char={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let v_0_1: DiffTrace = ({ let mut diff_r = vec![vec![DiffTrace(1), DiffTrace(2), DiffTrace(3)], Vec::<DiffTrace>::new()]; let diff_d = vec![vec![DiffTrace(4); 1usize], Vec::<DiffTrace>::new()]; let diff_n = diff_r.len().min(diff_d.len()); diff_r[..diff_n].clone_from_slice(&diff_d[..diff_n]); diff_r }).concat()[(diff_opaque_u64(1) as usize)].clone();
}
