// generated by rustscript-differential, seed 20718106939

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i16 {
    fn diff_describe(&self) -> String {
        format!("i16={:?}", self)
    }
}

impl DiffDescribe for f64 {
    fn diff_describe(&self) -> String {
        format!("f64={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn main() {
    let v_0_14: i8 = (diff_opaque_i64(0) as i8);
    let mut diff_cl_0_15 = |(diff_pa_0_16, diff_pb_0_17): (i8, String), diff_p_0_18: f64| -> i8 { v_0_14.rotate_right((diff_opaque_u64(3) as u32)) };
    println!("diff_cl_0_15_0: {:?}", diff_cl_0_15((v_0_14, String::from("")), diff_opaque_f64(0.0f64)));
}
