// generated by rustscript-differential, seed 20712100565

use std::collections::HashSet;

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i8 {
    fn diff_describe(&self) -> String {
        format!("i8={:?}", self)
    }
}

impl DiffDescribe for i32 {
    fn diff_describe(&self) -> String {
        format!("i32={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

fn main() {
    let mut v_0_1: u32 = (({ let mut diff_sorted: Vec<i16> = HashSet::<i16>::new().into_iter().collect(); diff_sorted.sort(); diff_sorted }).into_iter().map(|diff_x_0_4| (diff_opaque_u64(0) as u32)).product());
    println!("lang_0_32: {:#2?}", (if (v_0_1 == std::mem::take(&mut v_0_1)) { Ok::<f32, String>(diff_opaque_f32(0.0f32)) } else { Vec::<Result<f32, String>>::new()[(diff_opaque_u64(2) as usize)].clone() }));
}
