// generated by rustscript-differential, seed 93303529

use std::collections::{HashMap, HashSet};

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i32 {
    fn diff_describe(&self) -> String {
        format!("i32={:?}", self)
    }
}

impl DiffDescribe for Vec<u8> {
    fn diff_describe(&self) -> String {
        format!("Vec[u8]={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum DiffErr0_0 {
    V0,
    V1,
    V2(u16),
    Parse(std::num::ParseIntError),
}

impl std::fmt::Display for DiffErr0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::V0 => f.pad(&format!("V0")),
            Self::V1 => f.pad(&format!("V1")),
            Self::V2(diff_p0) => f.pad(&format!("V2 {:_<x}", diff_p0)),
            Self::Parse(diff_p0) => f.pad(&format!("Parse {:>#10?}", diff_p0)),
        }
    }
}

impl DiffErr0_0 {
    fn diff_code(&self) -> u32 {
        (match (self.clone()) { DiffErr0_0::V0 => (((diff_opaque_u64(4294967295) as u32) << (diff_opaque_u64(2147483648) as u32)) / (diff_opaque_i64(32766) as i16).trailing_zeros()), DiffErr0_0::V1 => ((diff_opaque_i64(1) as i8).trailing_ones() - (diff_opaque_i64(-50) as i8).count_zeros()), DiffErr0_0::V2(diff_b_0_0) => ((-20i64..-14i64).map(|diff_x_0_1| (diff_opaque_u64(2) as u32)).sum::<u32>()), DiffErr0_0::Parse(diff_b_0_2) => (!(diff_opaque_u64(3535479164) as u32)), })
    }
}

impl From<u16> for DiffErr0_0 {
    fn from(value: u16) -> Self {
        Self::V2(value)
    }
}

impl From<std::num::ParseIntError> for DiffErr0_0 {
    fn from(value: std::num::ParseIntError) -> Self {
        Self::Parse(value)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
enum DiffE0_1 {
    #[default]
    V0,
    V1,
    V2(i8, char),
}

impl DiffE0_1 {
    fn diff_code(&self) -> usize {
        (match (self.clone()) { DiffE0_1::V0 => (!(&[] as &[i16]).len()), DiffE0_1::V1 => (match ("-99999999999999999999".trim_end_matches("  padded  ")) { "0" => (diff_opaque_u64(2) as usize).rem_euclid((diff_opaque_u64(1) as usize)), "key=value" => (({ let mut diff_set: HashSet<(u32, u64)> = HashSet::new(); diff_set.insert(((diff_opaque_u64(2) as u32), (diff_opaque_u64(13901619046719885670) as u64))); diff_set.insert(((diff_opaque_u64(0) as u32), (diff_opaque_u64(8380818988710897005) as u64))); diff_set }).into_iter().map(|diff_x_0_3| (diff_opaque_u64(15603848266935510830) as usize)).sum::<usize>()), _ => ((diff_opaque_u64(9223372036854775808) as usize) / (diff_opaque_u64(0) as usize)), }), DiffE0_1::V2(diff_b_0_4, diff_b_0_5) => (match ("true") { "inf" => (diff_opaque_u64(9223372036854775808) as usize), "-1" | "  padded  " => (diff_opaque_u64(18446744073709551614) as usize).isqrt(), "5" => vec![(diff_opaque_i64(-1) as i32), (diff_opaque_i64(1073741823) as i32), (diff_opaque_i64(-1) as i32)].chunks_exact(2).map(|c| c.len()).sum::<usize>(), _ => (!(diff_opaque_u64(18446744073709551615) as usize)), }), })
    }
}

fn diff_pick_0<T: Clone + std::fmt::Debug>(a: T, b: T, first: bool) -> T {
    if first { a } else { b }
}

fn diff_fn_0_52() -> f64 {
    diff_opaque_f64(0.0f64)
}

fn main() {
    let mut v_0_12 = String::from("");
    let v_0_13: String = std::mem::replace(&mut v_0_12, String::from("5 "));
    println!("lang_0_43: {0:?}", ({ let mut diff_obs: Vec<((i8, i8), String)> = diff_pick_0(HashMap::<(i8, i8), String>::new(), HashMap::<(i8, i8), String>::new(), (diff_pick_0("-1", v_0_12.as_str(), (!diff_opaque_true())) > (&v_0_12[0usize..1usize]))).into_iter().collect(); diff_obs.sort(); diff_obs }));
    let mut diff_i_0_47: usize = 0usize;
    while diff_i_0_47 < 2usize {
        diff_i_0_47 += 1usize;
        if let 13908515029266933081usize = (diff_opaque_u64(0) as usize) {
            let mut v_0_51: Vec<(u32, Option<i8>)> = Vec::new();
            for (diff_k_0_48, diff_v_0_49) in &(HashMap::<u32, Option<i8>>::new()) {
                v_0_51.push(((*diff_k_0_48), None::<i8>));
            }
            v_0_51.sort();
            let 16384i16 = (diff_opaque_i64(0) as i16) else {
                println!("lang_0_54: {:?}", diff_fn_0_52());
                continue;
            };
            let v_0_55: HashSet<i16> = HashSet::<i16>::new();
        } else {
            if let Ok(diff_b_0_60) = Vec::<Result<u64, DiffErr0_0>>::new()[(diff_opaque_u64(4) as usize)].clone() && diff_opaque_true() {
                let v_0_61: DiffE0_1 = DiffE0_1::V1;
                let v_0_62 = DiffTrace(2);
            }
            v_0_12 = v_0_13.clone();
        }
    }
}
