// generated by rustscript-differential, seed 1014744596650

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<bool> {
    fn diff_describe(&self) -> String {
        format!("Vec[bool]={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn main() {
    let diff_cl_0_1 = |diff_p_0_2: DiffTrace, diff_p_0_3: DiffTrace| -> bool { (!diff_opaque_true()) };
    println!("diff_cl_0_1_0: {:?}", (!diff_opaque_true()));
    let mut diff_i_0_16: usize = 0usize;
    loop {
        diff_i_0_16 += 1usize;
        if diff_i_0_16 > 2usize {
            break;
        }
        if diff_cl_0_1(DiffTrace(0), vec![DiffTrace(17); 1usize][(diff_opaque_u64(3) as usize)].clone()) {
            break;
        }
    }
}
