// generated by rustscript-differential, seed 3101329

use std::collections::HashSet;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i16 {
    fn diff_describe(&self) -> String {
        format!("i16={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn diff_opaque_char(value: char) -> char {
    value
}

fn main() {
    let mut diff_i_0_42: usize = 0usize;
    'diff_l_0_43: loop {
        diff_i_0_42 += 1usize;
        if diff_i_0_42 > 3usize {
            break;
        }
        let v_0_44 = ((diff_opaque_i64(0) as i32), (diff_opaque_u64(0) as u16), DiffTrace(0));
        let ' ' = diff_opaque_char('a') else {
            println!("lang_0_46: {:diff_w$?}", ({ let mut diff_r = ({ let mut diff_elems: Vec<(bool, Option<bool>, u64)> = HashSet::<(bool, Option<bool>, u64)>::new().symmetric_difference(&({ let mut diff_set: HashSet<(bool, Option<bool>, u64)> = HashSet::new(); diff_set.insert(((!diff_opaque_true()), Some(diff_opaque_true()), (diff_opaque_u64(0) as u64))); diff_set })).cloned().collect(); diff_elems.sort(); diff_elems }); let diff_d = vec![((!diff_opaque_true()), None::<bool>, (diff_opaque_u64(0) as u64))]; let diff_n = diff_r.len().min(diff_d.len()); diff_r[..diff_n].copy_from_slice(&diff_d[..diff_n]); diff_r }), diff_w = 10usize);
            continue;
        };
    }
}
