// generated by rustscript-differential, seed 77102594

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let diff_cl_0_2 = |(diff_pa_0_3, diff_pb_0_4): (String, u64)| -> i16 { ({ let mut diff_r = vec![(diff_opaque_i64(2) as i16); 3usize]; let mut diff_i = 0usize; diff_r.dedup_by_key(|_| { diff_i += 1; diff_i / 2 }); diff_r }).iter().copied().sum::<i16>() };
    println!("diff_cl_0_2_0: {:?}", diff_cl_0_2((String::from(""), (diff_opaque_u64(0) as u64))));
}
