// generated by rustscript-differential, seed 20709100038

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    println!("lang_0_39: {:diff_w$?}", ({ let mut sorted = vec![DiffTrace(2); 3usize]; sorted.sort(); sorted.dedup(); sorted })[(diff_opaque_u64(0) as usize)].clone(), diff_w = 6usize);
}
