// generated by rustscript-differential, seed 1159

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
struct DiffS0_1 {
    f0: i8,
    f1: Vec<i16>,
    f2: Option<i16>,
}

impl std::fmt::Display for DiffS0_1 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.pad(&format!("DiffS0_1 f0={:?} f1={:?} f2={:?}", self.f0, self.f1, self.f2))
    }
}

impl From<i8> for DiffS0_1 {
    fn from(value: i8) -> Self {
        Self { f0: value, ..Default::default() }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum DiffErr0_2 {
    V0,
    V1,
    V2,
    V3(u64, std::num::ParseFloatError),
    Parse(std::num::ParseIntError),
}

impl std::fmt::Display for DiffErr0_2 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::V0 => write!(f, "V0"),
            Self::V1 => write!(f, "V1"),
            Self::V2 => write!(f, "V2"),
            Self::V3(diff_p0, diff_p1) => write!(f, "V3 {:3X} {}", diff_p0, diff_p1),
            Self::Parse(diff_p0) => write!(f, "Parse {:?}", diff_p0),
        }
    }
}

impl DiffErr0_2 {
    fn diff_code(&self) -> f32 {
        (match (self.clone()) { DiffErr0_2::V0 => (match (DiffS0_1 { f0: (diff_opaque_i64(-1) as i8), f1: vec![(diff_opaque_i64(-32767) as i16)], f2: None::<i16> }) { DiffS0_1 { f1: diff_b_0_1, f2: diff_b_0_2, .. } => diff_opaque_f32(0.5f32), }), DiffErr0_2::V1 => (match (false) { true => diff_opaque_f32((-1.0f32)), false => diff_opaque_f32((-0.0f32)), }), DiffErr0_2::V2 => (diff_opaque_f32(f32::MAX) / (diff_opaque_f32(1.0f32) - diff_opaque_f32(f32::NAN))), DiffErr0_2::V3(diff_b_0_4, diff_b_0_5) => (diff_opaque_f32(f32::NAN).sqrt() / (diff_opaque_f32(f32::MIN) * diff_opaque_f32(f32::MAX))), DiffErr0_2::Parse(diff_b_0_6) => (if (true & true) { vec![diff_opaque_f32((-0.0f32)), diff_opaque_f32((-909.432f32)), diff_opaque_f32(f32::NEG_INFINITY)].iter().copied().product::<f32>() } else { <f32>::default() }), })
    }
}

impl From<std::num::ParseIntError> for DiffErr0_2 {
    fn from(value: std::num::ParseIntError) -> Self {
        Self::Parse(value)
    }
}

impl DiffDescribe for DiffErr0_2 {
    fn diff_describe(&self) -> String {
        format!("DiffErr0_2={:?}", self)
    }
}

fn main() {
    println!("lang_0_28: {:>}", (match ((Vec::<u32>::new().into_iter().map(|diff_x_0_22: u32| ((diff_opaque_i64(0) as i32), (diff_opaque_i64(0) as i16))).max()).unwrap_or_default()) { (diff_b_0_24, diff_b_0_25) => 'a', }));
    println!("lang_0_44: {:*>8}", Vec::<DiffErr0_2>::new()[(diff_opaque_u64(5) as usize)].clone());
}
