// generated by rustscript-differential, seed 1121

use std::collections::{HashMap, HashSet};

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

#[derive(Debug, Clone, PartialEq, Default)]
enum DiffE0_0 {
    #[default]
    V0,
    V1(String, Option<String>),
    V2((usize, i8)),
}

impl std::fmt::Display for DiffE0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::V0 => f.pad(&format!("V0")),
            Self::V1(diff_p0, diff_p1) => f.pad(&format!("V1 {:?} {:12?}", diff_p0, diff_p1)),
            Self::V2(diff_p0) => f.pad(&format!("V2 {:?}", diff_p0)),
        }
    }
}

impl DiffE0_0 {
    fn diff_code(&self) -> i32 {
        (match (self.clone()) { DiffE0_0::V0 => (({ let mut diff_sorted: Vec<i16> = (({ let mut diff_map: HashMap<i16, Option<i64>> = HashMap::new(); diff_map.insert((diff_opaque_i64(16384) as i16), Some((diff_opaque_i64(-9223372036854775808) as i64))); diff_map }).into_iter().collect::<HashMap<i16, Option<i64>>>()).into_keys().collect(); diff_sorted.sort(); diff_sorted }).into_iter().map(|diff_x_0_0: i16| (diff_opaque_i64(-2147483648) as i32).wrapping_pow((diff_opaque_u64(7) as u32))).sum::<i32>()), DiffE0_0::V1(diff_b_0_1, diff_b_0_2) => (({ let mut diff_sorted: Vec<Option<u8>> = HashSet::<Option<u8>>::new().into_iter().collect(); diff_sorted.sort(); diff_sorted }).into_iter().map(|diff_x_0_3| (diff_opaque_i64(2) as i32).isqrt()).fold(({ let mut diff_map: HashMap<bool, i32> = HashMap::new(); diff_map.insert(false, (diff_opaque_i64(1) as i32)); diff_map.insert(false, (diff_opaque_i64(2147483646) as i32)); diff_map }).get(&false).cloned().unwrap_or((diff_opaque_i64(-2147483647) as i32)), |diff_x_0_4, diff_x_0_5| diff_x_0_4)), DiffE0_0::V2(diff_b_0_6) => (diff_opaque_i64(2147483646) as i32).midpoint((if true { (diff_opaque_i64(-2147483648) as i32) } else { (diff_opaque_i64(-1) as i32) })), })
    }
}

impl From<(usize, i8)> for DiffE0_0 {
    fn from(value: (usize, i8)) -> Self {
        Self::V2(value)
    }
}

fn diff_factory_0_9(diff_n: i16) -> impl Fn(i16) -> i16 {
    move |diff_x: i16| (diff_x * diff_n)
}

fn main() {
    let diff_cl_0_8 = diff_factory_0_9(Err::<HashMap<String, i16>, DiffE0_0>(DiffE0_0::V0).unwrap_or(HashMap::<String, i16>::new()).get(&String::from("")).cloned().unwrap_or_default());
    println!("diff_cl_0_8_0: {:?}", (diff_opaque_i64(0) as i16).rem_euclid((diff_opaque_i64(0) as i16)));
}
