// generated by rustscript-differential, seed 5202381

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

mod diff_mod0 {
    use super::*;

    #[derive(Debug, Clone, PartialEq, Default)]
    pub enum DiffE0_0 {
        #[default]
        V0,
        V1(f64, i16),
        V2,
    }

    impl std::fmt::Display for DiffE0_0 {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            match self {
                Self::V0 => write!(f, "V0"),
                Self::V1(diff_p0, diff_p1) => write!(f, "V1 {:?} {:0X}", diff_p0, diff_p1),
                Self::V2 => write!(f, "V2"),
            }
        }
    }

    impl DiffE0_0 {
        pub fn diff_code(&self) -> i16 {
            (match (self.clone()) { DiffE0_0::V0 => ((diff_opaque_f64((-828.905f64)) as i16) >> ((diff_opaque_u64(4294967295) as u32) << (diff_opaque_u64(1251528365) as u32))), DiffE0_0::V1(diff_b_0_0, diff_b_0_1) => (diff_opaque_i64(0) as i16).min(diff_b_0_1).saturating_sub((match ((diff_opaque_i64(2147483646) as i32)) { diff_b_0_2 @ -1198633239i32 if diff_opaque_true() => diff_b_0_1, _ => (diff_opaque_i64(16384) as i16), })), DiffE0_0::V2 => (diff_opaque_i64(16383) as i16), })
        }
    }

    #[derive(Debug, Clone, PartialEq, Default)]
    pub struct DiffS0_1 {
        pub f0: DiffE0_0,
        pub f1: DiffTrace,
        pub f2: Option<i64>,
    }

    impl std::fmt::Display for DiffS0_1 {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "DiffS0_1 f0={:?} f1={:?} f2={:?}", self.f0, self.f1, self.f2)
        }
    }

}

fn main() {
    let mut diff_i_0_12: usize = 0usize;
    let v_0_11: Vec<diff_mod0::DiffS0_1> = loop {
        diff_i_0_12 += 1usize;
        if diff_i_0_12 > 3usize {
            break vec![diff_mod0::DiffS0_1 { ..Default::default() }];
        }
        if (!diff_opaque_true()) {
            break Vec::<diff_mod0::DiffS0_1>::new();
        }
    };
}
