// generated by rustscript-differential, seed 500000

fn main() {
    let v_0_0 = (&[] as &[u8]).len();
    println!("lang_0_1: {:?}", v_0_0);
    println!("lang_0_2: {:?}", (&[] as &[String]).to_vec());
}
