// generated by rustscript-differential, seed 20729100632

// structured mutation from seeds 20729100631 and 20729100632 using [BlockOrder, Splice, BlockOrder, BlockOrder]

use std::collections::HashMap;

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for bool {
    fn diff_describe(&self) -> String {
        format!("bool={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let mut v_1_14: usize = (diff_opaque_u64(0) as usize);
    let mut v_1_22: Vec<(Option<i16>, i16)> = Vec::new();
    for (diff_k_1_18, diff_v_1_19) in &(Some(({ let mut diff_map: HashMap<Option<i16>, i16> = HashMap::new(); diff_map.insert(None::<i16>, (diff_opaque_i64(2) as i16)); diff_map })).unwrap_or_default()) {
        v_1_22.push((None::<i16>, (*diff_v_1_19)));
    }
    v_1_22.sort();
    for (diff_i_1_26, diff_e_1_25) in v_1_22.iter().enumerate() {
        let v_1_28: usize = std::mem::replace(&mut v_1_14, diff_i_1_26);
    }
    println!("lang_1_36: {:diff_w$}", (!v_1_14), diff_w = 3usize);
}
