// generated by rustscript-differential, seed 20728219053

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for f32 {
    fn diff_describe(&self) -> String {
        format!("f32={:?}", self)
    }
}

impl DiffDescribe for u64 {
    fn diff_describe(&self) -> String {
        format!("u64={:?}", self)
    }
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum DiffErr0_0 {
    V0,
    V1,
    Parse(std::num::ParseIntError),
}

impl std::fmt::Display for DiffErr0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::V0 => f.pad(&format!("V0")),
            Self::V1 => f.pad(&format!("V1")),
            Self::Parse(diff_p0) => f.pad(&format!("Parse {:#?}", diff_p0)),
        }
    }
}

impl From<std::num::ParseIntError> for DiffErr0_0 {
    fn from(value: std::num::ParseIntError) -> Self {
        Self::Parse(value)
    }
}

impl DiffDescribe for DiffErr0_0 {
    fn diff_describe(&self) -> String {
        format!("DiffErr0_0={:?}", self)
    }
}

const DIFF_C0_1: bool = false;

fn main() {
    for (diff_i_0_11, diff_e_0_10) in (Some(DiffErr0_0::V1).into_iter().collect::<Vec<DiffErr0_0>>()).iter().enumerate() {
        println!("lang_0_14: {:?}", (match (Some(String::from("1"))) { Some(diff_b_0_13) if diff_i_0_11.is_power_of_two() => Err::<Vec<bool>, DiffErr0_0>((*diff_e_0_10).clone()), None => Ok::<Vec<bool>, DiffErr0_0>(vec![(if diff_opaque_true() { DIFF_C0_1 } else { false }); 3usize]), _ => Ok::<Vec<bool>, DiffErr0_0>(vec![(if diff_opaque_true() { DIFF_C0_1 } else { false }), (if diff_opaque_true() { DIFF_C0_1 } else { false })]), }).unwrap_or(Vec::<bool>::new()));
    }
}
