// generated by rustscript-differential, seed 20719003470

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<f64> {
    fn diff_describe(&self) -> String {
        format!("Vec[f64]={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn main() {
    {
        println!("lang_0_29: {:?}", ((-16i64..-12i64).map(|diff_x_0_24: i64| (match (((1i64..5i64).map(|diff_x_0_25: i64| ((diff_opaque_i64(0) as i32), DiffTrace(1), DiffTrace(2))).nth(3usize))) { Some((diff_b_0_26, diff_b_0_27, diff_b_0_28)) if (!diff_opaque_true()) => <(Option<f64>, u8)>::default(), _ => Vec::<(Option<f64>, u8)>::new()[(diff_opaque_u64(4) as usize)].clone(), })).last()));
    }
}
