// generated by rustscript-differential, seed 20713200270

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u8 {
    fn diff_describe(&self) -> String {
        format!("u8={:?}", self)
    }
}

impl DiffDescribe for f32 {
    fn diff_describe(&self) -> String {
        format!("f32={:?}", self)
    }
}

fn main() {
    let v_0_11: usize = vec![vec![DiffTrace(1); 2usize]].into_iter().flatten().count();
}
