// generated by rustscript-differential, seed 1301006

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i8 {
    fn diff_describe(&self) -> String {
        format!("i8={:?}", self)
    }
}

impl DiffDescribe for Vec<i8> {
    fn diff_describe(&self) -> String {
        format!("Vec[i8]={:?}", self)
    }
}

fn main() {
    'diff_l_0_17: for diff_e_0_16 in &(vec![DiffTrace(1)]) {
    }
}
