// generated by rustscript-differential, seed 9301755

use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<u32> {
    fn diff_describe(&self) -> String {
        format!("Vec[u32]={:?}", self)
    }
}

impl DiffDescribe for i8 {
    fn diff_describe(&self) -> String {
        format!("i8={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn diff_opaque_char(value: char) -> char {
    value
}

const DIFF_C0_0: f64 = f64::NAN;

fn main() {
    let v_0_7: bool = (!diff_opaque_true());
    println!("lang_0_50: {:.0}", (&(format!("{:?}", (match ((({ let mut diff_map: HashMap<i32, (u64, char)> = HashMap::new(); diff_map.insert((diff_opaque_i64(-1585991675) as i32), ((diff_opaque_u64(9223372036854775807) as u64), diff_opaque_char('é'))); diff_map }).into_values().map(|diff_x_0_48: (u64, char)| DiffTrace(1)).min())) { Some(ref diff_b_0_49) if v_0_7 => Some(diff_opaque_f64(327.7840000000001f64)).expect("differential expect"), None => ((if diff_opaque_true() { DIFF_C0_0 } else { 0.0f64 }) / (if diff_opaque_true() { DIFF_C0_0 } else { 0.0f64 })), _ => (diff_opaque_f64(f64::NAN) % (if diff_opaque_true() { DIFF_C0_0 } else { 0.0f64 })), }).abs().to_le_bytes()))[..2usize]));
}
