// generated by rustscript-differential, seed 500403

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_true() -> bool {
    true
}

fn diff_pick_0<T: Clone + std::fmt::Debug>(a: T, b: T, first: bool) -> T {
    if first { a } else { b }
}

fn diff_fn_0_31(diff_p_0_32: &str) -> Vec<usize> {
    if diff_p_0_32.eq_ignore_ascii_case(diff_pick_0(diff_p_0_32, diff_p_0_32, diff_opaque_true())) {
        return Vec::<usize>::new();
    }
    Vec::<usize>::new()
}

fn main() {
    {
        let v_0_30: Vec<usize> = diff_fn_0_31("");
    }
    println!("lang_0_44: {0:<1$?}", DiffTrace(0), 6usize);
}
