// generated by rustscript-differential, seed 18211

use std::collections::HashSet;

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<String> {
    fn diff_describe(&self) -> String {
        format!("Vec[String]={:?}", self)
    }
}

impl DiffDescribe for i64 {
    fn diff_describe(&self) -> String {
        format!("i64={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn diff_pick_0<T: Clone + std::fmt::Debug>(a: T, b: T, first: bool) -> T {
    if first { a } else { b }
}

fn diff_fn_0_29(diff_p_0_30: u8) -> HashSet<char> {
    HashSet::<char>::new()
}

fn main() {
    let v_0_0 = (diff_pick_0(None::<u16>, Some((diff_opaque_u64(65534) as u16)), diff_opaque_true()).unwrap_or_default() / (diff_opaque_u64(23895) as u16));
    let diff_cl_0_2 = |diff_p_0_3: u8, diff_p_0_4: u64| -> f32 { diff_opaque_f32(0.0f32) };
    println!("diff_cl_0_2_0: {:?}", diff_opaque_f32(0.0f32));
    println!("lang_0_33: {:?}", ({ let mut diff_obs: Vec<char> = diff_fn_0_29(((diff_opaque_u64(128) as u8) - (diff_opaque_u64(254) as u8))).into_iter().collect(); diff_obs.sort(); diff_obs }));
}
