// generated by rustscript-differential, seed 20705100147

use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<String> {
    fn diff_describe(&self) -> String {
        format!("Vec[String]={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
struct DiffS0_0 {
    f0: u8,
}

impl std::fmt::Display for DiffS0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.pad(&format!("DiffS0_0 f0={:011b}", self.f0))
    }
}

impl DiffS0_0 {
    fn diff_m0(&self) -> usize {
        (!(diff_opaque_u64(0) as usize).wrapping_mul((diff_opaque_u64(1) as usize)))
    }
    fn diff_m1(&self, diff_a_0_0: f32) -> Self {
        DiffS0_0 {
            f0: <u8>::default(),
        }
    }
    fn diff_new(diff_a_0_1: u8) -> Self {
        DiffS0_0 { f0: diff_a_0_1 }
    }
}

impl DiffDescribe for DiffS0_0 {
    fn diff_describe(&self) -> String {
        format!("DiffS0_0={:?}", self)
    }
}

fn diff_fn_0_3() -> Vec<DiffS0_0> {
    let diff_l_0_4 = HashMap::<i32, Option<i16>>::new();
    let diff_l_0_5 = ({
        let mut diff_map: HashMap<bool, DiffS0_0> = HashMap::new();
        diff_map.insert(
            diff_opaque_true(),
            DiffS0_0 {
                f0: (diff_opaque_u64(127) as u8),
            },
        );
        diff_map
    })
    .get(&diff_opaque_true())
    .cloned()
    .unwrap_or(
        (DiffS0_0 {
            f0: (diff_opaque_u64(177) as u8),
        })
        .diff_m1(diff_opaque_f32(f32::MIN)),
    );
    if (!diff_opaque_true()) {
        return Vec::<DiffS0_0>::new();
    }
    vec![diff_l_0_5.clone()]
}

fn main() {
    let v_0_2: Vec<DiffS0_0> = diff_fn_0_3();
    println!("lang_0_36: {:diff_w$?}", v_0_2, diff_w = 8usize);
    println!("lang_0_41: {:?}", (DiffTrace(0),));
}
