// generated by rustscript-differential, seed 586894887093

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

fn main() {
    let v_0_1: f32 = (vec![DiffTrace(1)].into_iter().map(|diff_x_0_2: DiffTrace| diff_opaque_f32(0.0f32)).fold((match (Some((DiffTrace(0), (diff_opaque_i64(0) as i64)))) { Some(diff_b_0_5) if Vec::<bool>::new()[(diff_opaque_u64(0) as usize)].clone() => diff_opaque_f32(0.0f32), _ => diff_opaque_f32(0.0f32), }), |diff_x_0_3, diff_x_0_4| diff_opaque_f32(0.0f32)));
}
