// generated by rustscript-differential, seed 20720000131

use std::collections::HashSet;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i8 {
    fn diff_describe(&self) -> String {
        format!("i8={:?}", self)
    }
}

impl DiffDescribe for f32 {
    fn diff_describe(&self) -> String {
        format!("f32={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let v_0_1 = <i64>::default();
    let v_0_4: i64 = (diff_opaque_i64(0) as i64);
    println!("lang_0_23: {:?}", Vec::<u64>::new().contains(&(match ((diff_opaque_u64(65534) as u16)) { diff_b_0_22 if (DiffTrace(1) >= DiffTrace(2)) => (diff_opaque_u64(9223372036854775808) as u64), 0u16..=0u16 if ({ let mut diff_set: HashSet<i64> = HashSet::new(); diff_set.insert(v_0_4); diff_set }).is_disjoint(&({ let mut diff_set: HashSet<i64> = HashSet::new(); diff_set.insert(v_0_1); diff_set })) => (diff_opaque_u64(0) as u64).saturating_sub((diff_opaque_u64(18446744073709551615) as u64)), _ => (!(diff_opaque_u64(12075545182432354721) as u64)), })));
}
