// generated by rustscript-differential, seed 20721119697

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<i64> {
    fn diff_describe(&self) -> String {
        format!("Vec[i64]={:?}", self)
    }
}

fn diff_opaque_true() -> bool {
    true
}

fn main() {
    for _ in 0usize..2usize {
        if let Some(diff_b_0_29) = vec![DiffTrace(4), DiffTrace(5)].first().cloned() {
            println!("lang_0_31: {0:?}", None::<Option<u64>>);
            let Err(diff_b_0_32) = Ok::<bool, std::num::ParseFloatError>((!diff_opaque_true())) else {
                println!("lang_0_33: {:?}", Vec::<(i32,)>::new());
                continue;
            };
        }
    }
}
