// generated by rustscript-differential, seed 5004

// structured mutation from seeds 5003 and 5004 using [BlockOrder, BlockOrder, Splice, BlockOrder]

use std::collections::HashMap;

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u32 {
    fn diff_describe(&self) -> String {
        format!("u32={:?}", self)
    }
}

impl DiffDescribe for Vec<u64> {
    fn diff_describe(&self) -> String {
        format!("Vec[u64]={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn main() {
    let v_1_15: bool = (vec![None::<usize>] <= Vec::<Vec<Option<usize>>>::new().concat());
    println!("lang_1_46: {0:~>4E}", diff_opaque_f64(0.0f64));
    let v_0_23: u16 = (Vec::<HashMap<u16, (u8, i64)>>::new()[(diff_opaque_u64(5) as usize)].clone().into_keys().sum::<u16>());
}
