// generated by rustscript-differential, seed 5060

// structured mutation from seeds 5059 and 5060 using [Splice, Splice, Splice]

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let v_0_13 = Vec::<f64>::new()[(diff_opaque_u64(17378032808971086138) as usize)].clone();
}
