// generated by rustscript-differential, seed 20705000001

use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let v_0_4 = (({
        let mut diff_map: HashMap<usize, Option<String>> = HashMap::new();
        diff_map.insert(
            (diff_opaque_u64(9223372036854775807) as usize),
            Some(String::from("TRUE")),
        );
        diff_map.insert(
            (diff_opaque_u64(16580901840749721458) as usize),
            Some(String::from("300")),
        );
        diff_map
    })
    .into_keys()
    .map(|diff_x_0_5| DiffTrace(1))
    .min())
    .unwrap_or_default();
}
