// generated by rustscript-differential, seed 20703100071

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn diff_opaque_char(value: char) -> char {
    value
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffS0_0 {
    f0: String,
    f1: DiffTrace,
}

impl DiffS0_0 {
    fn diff_m0(&self) -> u64 {
        (diff_opaque_u64(0) as u64)
    }
    fn diff_m1(&self) -> char {
        diff_opaque_char('ß')
    }
}

fn main() {
    println!("lang_0_5: {0:1$?}", ((DiffS0_0 { f0: String::from(""), f1: DiffTrace(0) }).f0.clone().eq_ignore_ascii_case(String::from("").as_str()) && (!diff_opaque_true())), 5usize);
}
