// generated by rustscript-differential, seed 20708014995

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u16 {
    fn diff_describe(&self) -> String {
        format!("u16={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let mut v_0_11: u16 = (diff_opaque_u64(1) as u16);
    println!("lang_0_48: {:+#0diff_w$}", (v_0_11 / std::mem::replace(&mut v_0_11, (diff_opaque_u64(2) as u16))), diff_w = 1usize);
}
