// generated by rustscript-differential, seed 20719118909

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn diff_write_0_4(diff_target: &mut DiffTrace) {
    let diff_cur: DiffTrace = diff_target.clone();
    *diff_target = DiffTrace(0);
}

fn diff_fn_0_5(diff_p_0_6: f64, diff_p_0_7: i8) -> DiffTrace {
    DiffTrace(0)
}

fn main() {
    let mut v_0_0: u16 = (diff_opaque_u64(0) as u16);
    let mut diff_cl_0_1 = move || -> u16 { v_0_0 ^= v_0_0; v_0_0 };
    println!("diff_cl_0_1_0: {:?}", diff_cl_0_1());
    let mut v_0_0: DiffTrace = DiffTrace(0);
    diff_write_0_4(&mut v_0_0);
    println!("lang_0_10: {:?}", diff_fn_0_5(diff_opaque_f64(0.0f64), ((diff_opaque_i64(0) as i8) & (diff_opaque_i64(126) as i8)).clamp((-(diff_opaque_i64(-127) as i8)), (diff_opaque_i64(-94) as i8))));
}
