// generated by rustscript-differential, seed 20702000011

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_write_0_9(diff_target: &mut DiffTrace, diff_p_0_10: u64) {
    let diff_cur: DiffTrace = diff_target.clone();
    *diff_target = Vec::<DiffTrace>::new()[(diff_opaque_u64(2) as usize)].clone();
}

fn main() {
    let mut v_0_0 = DiffTrace(0);
    diff_write_0_9(&mut v_0_0, (diff_opaque_u64(0) as u64));
}
