// generated by rustscript-differential, seed 20720000333

use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
enum DiffE0_0 {
    #[default]
    V0,
    V1(Vec<u8>, String),
    V2,
}

fn diff_fn_0_10(diff_p_0_11_ref: &DiffE0_0, diff_p_0_12_ref: &DiffTrace) -> Vec<i16> {
    let diff_p_0_11: DiffE0_0 = diff_p_0_11_ref.clone();
    let diff_p_0_12: DiffTrace = diff_p_0_12_ref.clone();
    let diff_l_0_13: HashMap<u16, Option<u16>> = Vec::<HashMap<u16, Option<u16>>>::new()[(diff_opaque_u64(1) as usize)].clone();
    let diff_l_0_14 = DiffE0_0::V0;
    if diff_opaque_true() {
        return Vec::<i16>::new();
    }
    Vec::<i16>::new()
}

fn main() {
    let v_0_9: Vec<i16> = diff_fn_0_10(&(DiffE0_0::V0), &(DiffTrace(0)));
}
