// generated by rustscript-differential, seed 20719100315

use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for f32 {
    fn diff_describe(&self) -> String {
        format!("f32={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn diff_opaque_char(value: char) -> char {
    value
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
enum DiffE0_0 {
    #[default]
    V0,
    V1(i32, Vec<u8>),
}

impl DiffDescribe for DiffE0_0 {
    fn diff_describe(&self) -> String {
        format!("DiffE0_0={:?}", self)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum DiffErr0_1 {
    V0,
    V1,
    V2(char),
    Parse(std::num::ParseIntError),
}

impl std::fmt::Display for DiffErr0_1 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::V0 => write!(f, "V0"),
            Self::V1 => write!(f, "V1"),
            Self::V2(diff_p0) => write!(f, "V2 {:?}", diff_p0),
            Self::Parse(diff_p0) => write!(f, "Parse {:?}", diff_p0),
        }
    }
}

impl DiffErr0_1 {
    fn diff_code(&self) -> f64 {
        (match (self.clone()) { DiffErr0_1::V0 => ((match (diff_opaque_char('7')) { 'f' => diff_opaque_f32(f32::MAX), '_' => diff_opaque_f32(f32::EPSILON), _ => diff_opaque_f32(f32::MIN), }) as f64), DiffErr0_1::V1 => <f64>::default().min((-diff_opaque_f64(f64::INFINITY))), DiffErr0_1::V2(diff_b_0_0) => diff_opaque_f64(0.5f64).trunc().div_euclid(diff_opaque_f64(0.5f64).copysign(diff_opaque_f64(f64::MIN))), DiffErr0_1::Parse(diff_b_0_1) => diff_opaque_f64(0.0f64), })
    }
}

impl From<char> for DiffErr0_1 {
    fn from(value: char) -> Self {
        Self::V2(value)
    }
}

impl From<std::num::ParseIntError> for DiffErr0_1 {
    fn from(value: std::num::ParseIntError) -> Self {
        Self::Parse(value)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
enum DiffE0_2 {
    #[default]
    V0,
    V1,
    V2,
}

impl DiffDescribe for DiffE0_2 {
    fn diff_describe(&self) -> String {
        format!("DiffE0_2={:?}", self)
    }
}

const DIFF_C0_0: u32 = 360501691u32;

fn diff_fn_0_3(diff_p_0_4: bool) -> f32 {
    let diff_l_0_5: DiffTrace = DiffTrace(0);
    diff_opaque_f32(0.0f32)
}

fn diff_factory_0_8(diff_n: i64) -> impl Fn(i64) -> i64 {
    move |diff_x: i64| (diff_x * diff_n)
}

fn diff_apply_0_12<F: FnMut(i64) -> i64>(f: &mut F, x: i64) -> i64 {
    f(x)
}

fn diff_pick_0<T: Clone + std::fmt::Debug>(a: T, b: T, first: bool) -> T {
    if first { a } else { b }
}

fn main() {
    let v_0_2 = diff_opaque_f32(0.0f32);
    let mut diff_cl_0_7 = diff_factory_0_8((diff_opaque_i64(0) as i64));
    println!("diff_cl_0_7_0: {:?}", diff_apply_0_12(&mut diff_cl_0_7, (diff_opaque_i64(0) as i64)));
    println!("diff_cl_0_7_1: {:?}", diff_apply_0_12(&mut diff_cl_0_7, (diff_opaque_i64(0) as i64)));
    let v_0_2: i64 = (Vec::<i32>::new().into_iter().map(|diff_x_0_13: i32| diff_apply_0_12(&mut diff_cl_0_7, (diff_opaque_i64(2) as i64))).fold((diff_opaque_i64(0) as i64), |diff_x_0_14, diff_x_0_15| (diff_opaque_i64(0) as i64)));
    println!("lang_0_16: {:?}", DiffE0_2::V2);
    {
    }
    {
    }
    println!("lang_0_19: {:?}", DiffE0_0::V0);
    println!("lang_0_20: {0:?} {0:?}", v_0_2);
    println!("lang_0_21: {0:1$?}", Vec::<i8>::new(), 8usize);
    println!("lang_0_22: {:->?}", diff_opaque_f64(0.5f64));
    println!("lang_0_25: {:?}", (diff_opaque_f64(0.0f64),));
    println!("lang_0_26: {:?}", HashMap::<i64, Vec<bool>>::new().get(&Vec::<i64>::new()[(diff_opaque_u64(5) as usize)].clone()).cloned().unwrap_or(vec![diff_opaque_true(), diff_opaque_true(), diff_opaque_true()]).get((diff_opaque_u64(4) as usize)).cloned());
}
