// generated by rustscript-differential, seed 20719113803

use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u16 {
    fn diff_describe(&self) -> String {
        format!("u16={:?}", self)
    }
}

impl DiffDescribe for Vec<u16> {
    fn diff_describe(&self) -> String {
        format!("Vec[u16]={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn diff_fn_0_29() -> i8 {
    (diff_opaque_i64(0) as i8)
}

fn main() {
    let mut v_0_10: Option<DiffTrace> = None::<DiffTrace>;
    {
        if let Some(diff_b_0_23) = (diff_opaque_u64(0) as usize).checked_shr((diff_opaque_u64(3) as u32)) && (!matches!(Some(DiffTrace(1)), Some(diff_b_0_24) if (!diff_opaque_true()))) {
            match (Ok::<Vec<f32>, std::num::ParseFloatError>(Vec::<f32>::new())) {
                Ok(diff_b_0_25) => {
                    println!("lang_0_27: {:?}", Vec::<f64>::new());
                    let v_0_28 = diff_fn_0_29();
                    v_0_10.take();
                }
                Err(diff_b_0_26) => {
                    let mut v_0_32: HashMap<String, i64> = HashMap::<String, i64>::new();
                    let v_0_34: u32 = (diff_opaque_u64(0) as u32);
                    v_0_32.insert(String::from(""), (diff_opaque_i64(0) as i64));
                }
            }
        } else {
            println!("lang_0_35: {:?}", DiffTrace(0));
            println!("lang_0_44: {:_^?}", Vec::<Option<i16>>::new());
        }
    }
}
