// generated by rustscript-differential, seed 20707113539

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for f32 {
    fn diff_describe(&self) -> String {
        format!("f32={:?}", self)
    }
}

impl DiffDescribe for Vec<i32> {
    fn diff_describe(&self) -> String {
        format!("Vec[i32]={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let (v_0_5, v_0_6, mut v_0_7) = ((diff_opaque_u64(0) as u16), (diff_opaque_i64(0) as i8), (diff_opaque_u64(0) as u8));
    let mut diff_i_0_8: usize = 0usize;
    loop {
        diff_i_0_8 += 1usize;
        if diff_i_0_8 > 3usize {
            break;
        }
        println!("lang_0_9: {:?}", ((diff_opaque_u64(2) as u8) % (std::mem::replace(&mut v_0_7, (diff_opaque_u64(78) as u8)) ^ v_0_7)));
        let mut diff_cl_0_10 = |diff_p_0_11: u16| -> u8 { v_0_7 += v_0_7; v_0_7 };
        println!("diff_cl_0_10_0: {:?}", diff_cl_0_10((diff_opaque_u64(0) as u16)));
    }
}
