// generated by rustscript-differential, seed 20714015478

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u64 {
    fn diff_describe(&self) -> String {
        format!("u64={:?}", self)
    }
}

impl DiffDescribe for Vec<f32> {
    fn diff_describe(&self) -> String {
        format!("Vec[f32]={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn main() {
    let mut v_0_8: i8 = (diff_opaque_i64(0) as i8);
    let mut diff_i_0_20: usize = 0usize;
    while diff_i_0_20 < 2usize {
        diff_i_0_20 += 1usize;
        v_0_8 = (diff_opaque_i64(-30) as i8);
        let mut diff_cl_0_22 = || -> i8 { v_0_8 += v_0_8; v_0_8 };
        println!("diff_cl_0_22_0: {:?}", diff_cl_0_22());
    }
}
