// generated by rustscript-differential, seed 20729210832

// structured mutation from seeds 20729210831 and 20729210832 using [Splice, BlockOrder, Splice]

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    'diff_l_1_11: for diff_e_1_10 in &((&(vec![DiffTrace(1005), DiffTrace(1006)])[1usize..]).iter().rev().cloned().collect::<Vec<DiffTrace>>()) {
        let Some(diff_b_1_13) = None::<i16> else {
            println!("lang_1_16: {0:?} {0:?}", Vec::<String>::new()[(diff_opaque_u64(5) as usize)].clone());
            break 'diff_l_1_11;
        };
    }
}
