// generated by rustscript-differential, seed 20729211983

use std::collections::HashSet;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for bool {
    fn diff_describe(&self) -> String {
        format!("bool={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
enum DiffE0_0 {
    V0,
    V1,
    V2,
    V3,
}

impl std::fmt::Display for DiffE0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::V0 => write!(f, "V0"),
            Self::V1 => write!(f, "V1"),
            Self::V2 => write!(f, "V2"),
            Self::V3 => write!(f, "V3"),
        }
    }
}

impl DiffDescribe for DiffE0_0 {
    fn diff_describe(&self) -> String {
        format!("DiffE0_0={:?}", self)
    }
}

#[derive(Debug, Clone, PartialEq, Default)]
struct DiffS0_1 {
    f0: Vec<bool>,
    f1: i64,
    f2: f32,
}

impl std::fmt::Display for DiffS0_1 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.pad(&format!("DiffS0_1 f0={:?} f1={:#04?} f2={:_<#6e}", self.f0, self.f1, self.f2))
    }
}

impl DiffS0_1 {
    fn diff_m0(&self, diff_a_0_0: usize) -> Self {
        (if (({ let mut diff_set: HashSet<DiffE0_0> = HashSet::new(); diff_set.insert(DiffE0_0::V0); diff_set }).into_iter().all(|diff_ref| { let diff_x_0_1: DiffE0_0 = diff_ref.clone(); diff_opaque_true() })) { DiffS0_1 { f0: vec![diff_opaque_true(), diff_opaque_true(), (!diff_opaque_true())], f1: self.f1, f2: diff_opaque_f32((-1.0f32)) } } else { Some(DiffS0_1 { f0: vec![(!diff_opaque_true()); 1usize], f1: self.f1, f2: diff_opaque_f32(0.5f32) }).unwrap_or(DiffS0_1 { f0: vec![(!diff_opaque_true())], f1: self.f1, f2: self.f2 }) })
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
struct DiffS0_2 {
    f0: (String, usize),
    f1: i8,
}

impl std::fmt::Display for DiffS0_2 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "DiffS0_2 f0={:?} f1={:^+#08}", self.f0, self.f1)
    }
}

impl DiffS0_2 {
    fn diff_m0(&self) -> i8 {
        vec![(diff_opaque_i64(-1) as i8), self.f1].iter().copied().sum::<i8>()
    }
    fn diff_m1(&self, diff_a_0_2: f32) -> bool {
        (if <bool>::default() { String::from("0").contains("99999999999999999999") } else { (diff_opaque_true() != (!diff_opaque_true())) })
    }
    fn diff_new(diff_a_0_3: (String, usize), diff_a_0_4: i8) -> Self {
        DiffS0_2 { f0: diff_a_0_3, f1: diff_a_0_4 }
    }
}

fn diff_factory_0_20(diff_n: i32) -> impl Fn(i32) -> i32 {
    move |diff_x: i32| (diff_x * diff_n)
}

fn main() {
    let v_0_5 = HashSet::<u32>::new();
    let v_0_6: Option<(&str, &str)> = None::<(&str, &str)>;
    let v_0_5 = (diff_opaque_u64(0) as u16);
    let mut v_0_9 = HashSet::<i64>::new();
    {
    }
    for diff_e_0_13 in &(Some(vec![DiffTrace(2); 3usize]).unwrap_or(vec![vec![DiffTrace(3); 1usize]].concat())) {
        for (diff_i_0_18, diff_e_0_17) in (({ let mut diff_elems: Vec<u32> = HashSet::<u32>::new().union(&({ let mut diff_set: HashSet<u32> = HashSet::new(); diff_set.insert((diff_opaque_u64(0) as u32)); diff_set })).cloned().collect(); diff_elems.sort(); diff_elems })).iter().enumerate() {
            v_0_9 = v_0_9.clone();
            v_0_9.insert((diff_opaque_i64(0) as i64));
            let diff_cl_0_19 = diff_factory_0_20((diff_opaque_i64(2147483647) as i32));
            println!("diff_cl_0_19_0: {:?}", (diff_opaque_i64(0) as i32));
            println!("diff_cl_0_19_1: {:?}", diff_cl_0_19((!(diff_opaque_i64(1) as i32))));
        }
    }
    {
    }
    {
    }
    println!("lang_0_36: {0:>X}", (diff_opaque_i64(0) as i8));
    println!("lang_0_37: {:<#7?}", (!diff_opaque_true()));
    println!("lang_0_38: {:?}", v_0_6);
    println!("lang_0_39: {:#diff_w$E}", v_0_5, diff_w = 11usize);
    println!("lang_0_40: {:?}", ({ let mut diff_obs: Vec<i64> = v_0_9.clone().into_iter().collect(); diff_obs.sort(); diff_obs }));
    println!("lang_0_41: {:?}", (diff_opaque_u64(0) as usize));
    println!("lang_0_42: {:?}", Ok::<i64, std::num::ParseFloatError>((diff_opaque_i64(0) as i64)));
    println!("lang_0_46: {:?}", DiffS0_2 { f0: (String::from(""), (diff_opaque_u64(0) as usize)), f1: (diff_opaque_i64(0) as i8) });
    println!("lang_0_47: {:+12?}", (diff_opaque_i64(0) as i16));
}
