// generated by rustscript-differential, seed 20719202273

use std::collections::HashSet;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<u32> {
    fn diff_describe(&self) -> String {
        format!("Vec[u32]={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn main() {
    let v_0_17: DiffTrace = DiffTrace(0);
    {
        match (('a', 0usize)) {
            (diff_b_0_42, diff_b_0_43) => {
                println!("lang_0_44: {0:<1$?}", DiffTrace(0), 0usize);
                println!("lang_0_47: {0:_>#6?}", ({ let mut diff_obs: Vec<u16> = HashSet::<u16>::new().into_iter().collect(); diff_obs.sort(); diff_obs }));
                println!("lang_0_50: {0:?}", matches!(Some(None::<u64>), Some(diff_b_0_48) if (match (vec![v_0_17.clone(), DiffTrace(12), DiffTrace(13)]).as_slice() { [diff_b_0_49] => { let diff_b_0_49: DiffTrace = diff_b_0_49.clone(); ((diff_opaque_u64(18446744073709551615) as usize) > (diff_opaque_u64(9223372036854775807) as usize)) }, _ => (diff_opaque_true() & diff_opaque_true()), })));
            }
        }
    }
}
