// generated by rustscript-differential, seed 20705000173

use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn diff_opaque_char(value: char) -> char {
    value
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
enum DiffE0_0 {
    #[default]
    V0,
    V1(i8),
    V2((usize, u32)),
    V3(usize, DiffTrace),
}

impl DiffE0_0 {
    fn diff_code(&self) -> i64 {
        (match (self.clone()) {
            DiffE0_0::V0 => {
                (match (Some(Err::<Vec<u64>, std::num::ParseFloatError>(
                    "x".parse::<f64>().unwrap_err(),
                ))
                .unwrap_or(Ok::<Vec<u64>, std::num::ParseFloatError>(
                    vec![(diff_opaque_u64(18446744073709551614) as u64); 2usize],
                ))) {
                    Ok(diff_b_0_0) => (diff_opaque_i64(2) as i64),
                    Err(diff_b_0_1) => (diff_opaque_i64(4611686018427387903) as i64),
                })
            }
            DiffE0_0::V1(diff_b_0_2) => {
                ((diff_opaque_i64(-8813939822986360006) as i64)
                    .rotate_right((diff_opaque_u64(4) as u32))
                    << (vec![(diff_opaque_i64(2147483647) as i32); 0usize]
                        .into_iter()
                        .map(|diff_x_0_3| (diff_opaque_u64(4294967294) as u32))
                        .product::<u32>()))
            }
            DiffE0_0::V2(diff_b_0_4) => {
                ((match (!diff_opaque_true()) {
                    true => vec![
                        (diff_opaque_i64(126) as i8),
                        (diff_opaque_i64(78) as i8),
                        (diff_opaque_i64(69) as i8),
                    ],
                    false => vec![(diff_opaque_i64(-127) as i8), (diff_opaque_i64(1) as i8)],
                })
                .into_iter()
                .map(|diff_x_0_5| {
                    vec![(diff_opaque_i64(4671010606866527994) as i64); 1usize]
                        .iter()
                        .copied()
                        .sum::<i64>()
                })
                .sum::<i64>())
            }
            DiffE0_0::V3(diff_b_0_6, diff_b_0_7) => ((-14i64..-13i64).sum::<i64>()),
        })
    }
}

impl From<i8> for DiffE0_0 {
    fn from(value: i8) -> Self {
        Self::V1(value)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
enum DiffE0_1 {
    #[default]
    V0,
    V1,
}

impl DiffE0_1 {
    fn diff_code(&self) -> usize {
        (match (self.clone()) {
            DiffE0_1::V0 => {
                (({
                    let mut diff_values: Vec<(char,)> = ({
                        let mut diff_map: HashMap<Option<i64>, (char,)> = HashMap::new();
                        diff_map.insert(None::<i64>, (diff_opaque_char('é'),));
                        diff_map.insert(None::<i64>, (diff_opaque_char('\t'),));
                        diff_map.insert(
                            Some((diff_opaque_i64(4611686018427387903) as i64)),
                            (diff_opaque_char('7'),),
                        );
                        diff_map
                    })
                    .into_values()
                    .collect();
                    diff_values.sort();
                    diff_values
                })
                .into_iter()
                .map(|diff_x_0_8: (char,)| (!(diff_opaque_u64(18446744073709551614) as usize)))
                .sum::<usize>())
            }
            DiffE0_1::V1 => {
                (({
                    let mut diff_sorted: Vec<u64> = ({
                        let mut diff_map: HashMap<u64, u64> = HashMap::new();
                        diff_map.insert(
                            (diff_opaque_u64(9223372036854775808) as u64),
                            (diff_opaque_u64(9223372036854775807) as u64),
                        );
                        diff_map.insert((diff_opaque_u64(1) as u64), (diff_opaque_u64(1) as u64));
                        diff_map
                    })
                    .into_keys()
                    .collect();
                    diff_sorted.sort();
                    diff_sorted
                })
                .into_iter()
                .map(|diff_x_0_9: u64| {
                    ((diff_opaque_u64(6748199059537981461) as usize)
                        - (diff_opaque_u64(0) as usize))
                })
                .sum::<usize>())
            }
        })
    }
}

fn main() {
    println!(
        "lang_0_15: {:?}",
        (match (DiffE0_1::V0) {
            _ => vec![
                DiffE0_0::V3(
                    (diff_opaque_u64(18446744073709551614) as usize),
                    DiffTrace(2)
                );
                2usize
            ][(diff_opaque_u64(1) as usize)]
                .clone(),
        })
    );
}
