// generated by rustscript-differential, seed 1445153839584

// structured mutation from seeds 1445153839583 and 1445153839584 using [BlockOrder, BlockOrder]

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u16 {
    fn diff_describe(&self) -> String {
        format!("u16={:?}", self)
    }
}

impl DiffDescribe for i16 {
    fn diff_describe(&self) -> String {
        format!("i16={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

#[derive(Debug, Clone, PartialEq, Default)]
struct DiffS0_0 {
    f0: u32,
    f1: (usize, f64),
}

impl std::fmt::Display for DiffS0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.pad(&format!("DiffS0_0 f0={:>6o} f1={:?}", self.f0, self.f1))
    }
}

impl From<u32> for DiffS0_0 {
    fn from(value: u32) -> Self {
        Self { f0: value, ..Default::default() }
    }
}

impl DiffDescribe for DiffS0_0 {
    fn diff_describe(&self) -> String {
        format!("DiffS0_0={:?}", self)
    }
}

#[derive(Debug, Clone, PartialEq)]
struct DiffS0_1 {
    f0: (i32, usize),
    f1: i8,
    f2: DiffTrace,
}

impl DiffS0_1 {
    fn diff_new(diff_a_0_0: (i32, usize), diff_a_0_1: i8) -> Self {
        DiffS0_1 { f0: diff_a_0_0, f1: diff_a_0_1, f2: DiffTrace(1) }
    }
}

impl From<i8> for DiffS0_1 {
    fn from(value: i8) -> Self {
        Self { f0: (0i32, 0usize), f1: value, f2: DiffTrace(0) }
    }
}

fn main() {
    let mut v_0_12 = DiffS0_1 { f0: ((diff_opaque_i64(0) as i32), (diff_opaque_u64(0) as usize)), f1: (diff_opaque_i64(0) as i8), f2: DiffTrace(0) };
    v_0_12 = DiffS0_1 { f0: ((diff_opaque_i64(0) as i32), (diff_opaque_u64(0) as usize)), f1: (diff_opaque_i64(0) as i8), f2: (match (v_0_12) { DiffS0_1 { f0: diff_b_0_14, f1: 99i8..=113i8, .. } => DiffTrace(5), _ => DiffTrace(6), }) };
    println!("lang_0_35: {:diff_w$}", None::<DiffS0_0>.unwrap_or_default(), diff_w = 12usize);
}
