// generated by rustscript-differential, seed 1445153946874

use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
enum DiffE0_2 {
    #[default]
    V0,
    V1(Option<u32>, usize),
    V2,
    V3(u8),
}

impl From<u8> for DiffE0_2 {
    fn from(value: u8) -> Self {
        Self::V3(value)
    }
}

impl DiffDescribe for DiffE0_2 {
    fn diff_describe(&self) -> String {
        format!("DiffE0_2={:?}", self)
    }
}

fn main() {
    let mut v_0_10: Option<DiffTrace> = vec![DiffTrace(3)].iter().max().cloned();
    let v_0_16: DiffE0_2 = HashMap::<Option<String>, DiffE0_2>::new().get(&(match (v_0_10) { Some(diff_b_0_17) if (!diff_opaque_true()) => Some(String::from("a\nb\nc")), None => Some(String::from("+7")), _ => Some(String::from("  ")), })).cloned().unwrap_or(DiffE0_2::V0);
    v_0_10 = None::<DiffTrace>;
    println!("lang_0_35: {:#0X}", (diff_opaque_u64(0) as u16));
}
