// generated by rustscript-differential, seed 20724202773

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for String {
    fn diff_describe(&self) -> String {
        format!("String={:?}", self)
    }
}

impl DiffDescribe for Vec<u32> {
    fn diff_describe(&self) -> String {
        format!("Vec[u32]={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffS0_0 {
    f0: DiffTrace,
    f1: u64,
    f2: u64,
}

impl DiffS0_0 {
    fn diff_m0(&self) -> u8 {
        (diff_opaque_u64(71) as u8).wrapping_add((diff_opaque_u64(255) as u8)).midpoint((diff_opaque_u64(254) as u8).swap_bytes())
    }
}

fn main() {
    let mut v_0_0: DiffS0_0 = DiffS0_0 { f0: DiffTrace(1), ..Default::default() };
    let v_0_3 = (match (v_0_0) { DiffS0_0 { f2: diff_b_0_4, .. } => (diff_opaque_i64(0) as i8), });
    v_0_0 = DiffS0_0 { f0: DiffTrace(0), f1: (diff_opaque_u64(0) as u64), f2: (diff_opaque_u64(0) as u64) };
    println!("lang_0_26: {:?}", diff_opaque_f64(0.0f64));
}
