// generated by rustscript-differential, seed 20705100002

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i64 {
    fn diff_describe(&self) -> String {
        format!("i64={:?}", self)
    }
}

impl DiffDescribe for usize {
    fn diff_describe(&self) -> String {
        format!("usize={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
struct DiffS0_1 {
    f0: DiffTrace,
    f1: DiffTrace,
    f2: Option<i16>,
}

impl DiffS0_1 {
    fn diff_m0(&self) -> u32 {
        (if diff_opaque_f32(f32::EPSILON).is_infinite() {
            ((diff_opaque_u64(0) as u32) / (diff_opaque_u64(2147483647) as u32))
        } else {
            (if (!diff_opaque_true()) {
                (diff_opaque_u64(2147483647) as u32)
            } else {
                (diff_opaque_u64(4294967295) as u32)
            })
        })
    }
}

fn diff_pick_0<T: Clone + std::fmt::Debug>(a: T, b: T, first: bool) -> T {
    if first { a } else { b }
}

fn diff_fn_0_30(diff_p_0_31: f64, diff_p_0_32_ref: &i64) -> i8 {
    let diff_p_0_32: i64 = diff_p_0_32_ref.clone();
    (diff_opaque_i64(0) as i8)
}

fn main() {
    println!(
        "lang_0_36: {:0<6o}",
        diff_fn_0_30(
            (match (DiffS0_1 {
                f0: DiffTrace(1),
                f1: DiffTrace(2),
                f2: Some((diff_opaque_i64(32767) as i16))
            }) {
                DiffS0_1 {
                    f0: diff_b_0_35, ..
                } => None::<f64>,
            })
            .unwrap_or(
                (if diff_opaque_true() {
                    diff_opaque_f64(f64::EPSILON)
                } else {
                    diff_opaque_f64(0.0f64)
                })
            ),
            &(diff_opaque_i64(0) as i64)
        )
    );
}
