// generated by rustscript-differential, seed 700545

use diff_mod0 as diff_al0;

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i32 {
    fn diff_describe(&self) -> String {
        format!("i32={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn diff_opaque_char(value: char) -> char {
    value
}

mod diff_mod0 {
    use super::*;

    #[derive(Debug, Clone, PartialEq, Default)]
    pub enum DiffE0_0 {
        #[default]
        V0,
        V1(Option<usize>, f32),
        V2,
        V3(u64),
    }

    impl std::fmt::Display for DiffE0_0 {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            match self {
                Self::V0 => f.pad(&format!("V0")),
                Self::V1(diff_p0, diff_p1) => f.pad(&format!("V1 {:?} {:?}", diff_p0, diff_p1)),
                Self::V2 => f.pad(&format!("V2")),
                Self::V3(diff_p0) => f.pad(&format!("V3 {:=>3?}", diff_p0)),
            }
        }
    }

    impl DiffE0_0 {
        pub fn diff_code(&self) -> f64 {
            (match (self.clone()) { DiffE0_0::V0 => (vec![diff_opaque_f64(f64::NEG_INFINITY), diff_opaque_f64((-0.0f64))].iter().copied().sum::<f64>() - diff_opaque_f64(f64::INFINITY).ln()), DiffE0_0::V1(diff_b_0_0, diff_b_0_1) => diff_opaque_f64((-0.0f64)), DiffE0_0::V2 => diff_opaque_f64(f64::INFINITY), DiffE0_0::V3(diff_b_0_2) => (if (if diff_opaque_true() { diff_opaque_true() } else { (!diff_opaque_true()) }) { diff_opaque_f64(f64::MIN) } else { diff_opaque_f64(1.0f64).fract() }), })
        }
    }

    #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
    pub struct DiffS0_2 {
        pub f0: usize,
        pub f1: i32,
        pub f2: (char, i32),
    }

    impl std::fmt::Display for DiffS0_2 {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "DiffS0_2 f0={:_>#x} f1={:#4} f2={:?}", self.f0, self.f1, self.f2)
        }
    }

    impl DiffS0_2 {
        pub fn diff_m0(&self) -> Self {
            DiffS0_2 { f0: (diff_opaque_u64(9223372036854775807) as usize), f1: (diff_opaque_i64(-737856988) as i32), f2: self.f2 }
        }
    }

    pub fn diff_shared_0() -> DiffS0_2 {
        DiffS0_2 { f0: (diff_opaque_u64(0) as usize), f1: (diff_opaque_i64(0) as i32), f2: (diff_opaque_char('a'), (diff_opaque_i64(0) as i32)) }
    }

}

fn main() {
    let mut v_0_5: diff_al0::DiffS0_2 = diff_al0::diff_shared_0();
    let v_0_7: diff_al0::DiffS0_2 = std::mem::take(&mut v_0_5);
    v_0_5.f2 = (diff_opaque_char('a'), (diff_opaque_i64(0) as i32));
}
