// generated by rustscript-differential, seed 20713000338

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffS0_0 {
    f0: DiffTrace,
}

impl DiffS0_0 {
    fn diff_new(diff_a_0_0: DiffTrace) -> Self {
        DiffS0_0 { f0: diff_a_0_0 }
    }
}

fn main() {
    let v_0_1: DiffS0_0 = DiffS0_0 { f0: DiffTrace(0) };
    let diff_cl_0_14 = move |(diff_pa_0_15, diff_pb_0_16): (i32, f32), diff_p_0_17: u8| -> i16 { ([vec![v_0_1.clone(), v_0_1.clone()], vec![DiffS0_0 { f0: DiffTrace(11) }; 1usize]].concat().into_iter().map(|diff_x_0_18| (diff_opaque_i64(-22817) as i16)).sum::<i16>()) };
    println!("diff_cl_0_14_0: {:?}", diff_cl_0_14(((diff_opaque_i64(0) as i32), diff_opaque_f32(0.0f32)), (diff_opaque_u64(0) as u8)));
}
