// generated by rustscript-differential, seed 20724003173

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i16 {
    fn diff_describe(&self) -> String {
        format!("i16={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum DiffErr0_0 {
    V0,
    V1,
    V2(std::num::ParseIntError),
    V3(i64, std::num::ParseIntError),
}

impl std::fmt::Display for DiffErr0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::V0 => write!(f, "V0"),
            Self::V1 => write!(f, "V1"),
            Self::V2(diff_p0) => write!(f, "V2 {:?}", diff_p0),
            Self::V3(diff_p0, diff_p1) => write!(f, "V3 {:+01o} {:1?}", diff_p0, diff_p1),
        }
    }
}

impl From<std::num::ParseIntError> for DiffErr0_0 {
    fn from(value: std::num::ParseIntError) -> Self {
        Self::V2(value)
    }
}

fn main() {
    let v_0_6 = DiffTrace(1);
    {
        let diff_cl_0_31 = move |diff_p_0_32: i16, (diff_pa_0_33, diff_pb_0_34): (i16, u16)| -> usize { (vec![((diff_opaque_u64(1) as u16), (diff_opaque_i64(0) as i16), v_0_6.clone()); 3usize].into_iter().count()) };
        println!("diff_cl_0_31_0: {:?}", (diff_opaque_u64(0) as usize));
    }
    println!("lang_0_42: {:?}", Err::<i32, DiffErr0_0>(DiffErr0_0::V1));
}
