// generated by rustscript-differential, seed 20721009909

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u8 {
    fn diff_describe(&self) -> String {
        format!("u8={:?}", self)
    }
}

impl DiffDescribe for Vec<char> {
    fn diff_describe(&self) -> String {
        format!("Vec[char]={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
struct DiffS0_1 {
    f0: Option<usize>,
    f1: i32,
    f2: DiffTrace,
}

impl std::fmt::Display for DiffS0_1 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.pad(&format!("DiffS0_1 f0={:?} f1={:>#4e} f2={:>11?}", self.f0, self.f1, self.f2))
    }
}

impl DiffS0_1 {
    fn diff_m0(&self, diff_a_0_2: u16) -> bool {
        (match (Some((diff_opaque_i64(2147483647) as i32))) { Some(_) => (!diff_opaque_true()), None => <bool>::default(), })
    }
    fn diff_new(diff_a_0_3: Option<usize>, diff_a_0_4: i32) -> Self {
        DiffS0_1 { f0: diff_a_0_3, f1: diff_a_0_4, f2: DiffTrace(1) }
    }
}

impl From<i32> for DiffS0_1 {
    fn from(value: i32) -> Self {
        Self { f1: value, ..Default::default() }
    }
}

fn main() {
    let diff_cl_0_7 = move |diff_p_0_8: DiffTrace, diff_p_0_9: i8| -> i8 { diff_p_0_9 };
    println!("diff_cl_0_7_0: {:?}", (diff_opaque_i64(0) as i8));
    println!("diff_cl_0_7_1: {:?}", diff_cl_0_7((DiffS0_1 { f0: None::<usize>, f1: (diff_opaque_i64(0) as i32), f2: DiffTrace(0) }).f2, (vec![Some(diff_opaque_f64((-0.0f64))); 2usize].into_iter().map(|diff_x_0_12| (diff_opaque_i64(88) as i8)).product::<i8>())));
}
