// generated by rustscript-differential, seed 5037

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn main() {
    let v_0_1: i32 = (vec![(diff_opaque_u64(0) as u8)].into_iter().map(|diff_x_0_2| (-(if diff_opaque_true() { (-2147483648) } else { 0 }))).sum());
}
