// generated by rustscript-differential, seed 5037

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn main() {
    let v_0_1: i32 = (-(if diff_opaque_true() { (-2147483648) } else { 0 }));
    println!("lang_0_21: {:?}", Err::<f64, String>(String::from("")));
    println!("lang_0_23: {:?}", ((diff_opaque_u64(0) as u32) / (diff_opaque_u64(0) as u32)));
}
