// generated by rustscript-differential, seed 1300474

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn main() {
    let v_0_2: Vec<String> = Vec::<String>::new();
    let mut v_0_2: Vec<Option<i32>> = (vec![(diff_opaque_i64(0) as i8)].into_iter().map(|diff_x_0_9: i8| None::<i32>).collect());
    for diff_ref in v_0_2.iter_mut() {
        let diff_e_0_12: Option<i32> = diff_ref.clone();
        diff_ref.replace((diff_opaque_i64(0) as i32));
    }
}
