// generated by rustscript-differential, seed 20721207157

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i8 {
    fn diff_describe(&self) -> String {
        format!("i8={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
enum DiffE0_0 {
    #[default]
    V0,
    V1((bool, u64), u64),
}

impl DiffE0_0 {
    fn diff_code(&self) -> i16 {
        (match (self.clone()) { DiffE0_0::V0 => (diff_opaque_i64(32766) as i16), DiffE0_0::V1(diff_b_0_0, diff_b_0_1) => (diff_opaque_i64(32767) as i16), })
    }
}

fn main() {
    let v_0_3 = DiffE0_0::V0;
    let mut v_0_3: Vec<DiffE0_0> = Vec::<DiffE0_0>::new();
    let mut v_0_11: f64 = diff_opaque_f64(0.0f64);
    {
        match ((match ((diff_opaque_i64(0) as i64)) { -8520471370838551407i64..=6634517055226781855i64 | -7543625841172206267i64..4611686018427387903i64 | 5393416804879662605i64 if (vec![DiffTrace(7)].into_iter().any(|diff_ref| { let diff_x_0_16: DiffTrace = diff_ref.clone(); (!diff_opaque_true()) })) => Ok::<i16, String>((diff_opaque_i64(0) as i16)), _ => Ok::<i16, String>((diff_opaque_i64(0) as i16)), })) {
            Ok(diff_b_0_17) => {
                v_0_3 = Vec::<DiffE0_0>::new();
                println!("lang_0_19: {0:1$?}", ((!diff_opaque_true()), DiffTrace(8)), 2usize);
            }
            Err(diff_b_0_18) => {
                v_0_11 += v_0_11;
            }
        }
    }
}
