// generated by rustscript-differential, seed 20710200093

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    println!("lang_0_26: {0:?}", Ok::<DiffTrace, String>(DiffTrace(0)).unwrap_or(vec![DiffTrace(6)][(diff_opaque_u64(3) as usize)].clone()));
}
