// generated by rustscript-differential, seed 20695202191, reduced

fn diff_opaque(x: i64) -> i64 {
    x
}

fn main() {
    let mut diff_acc: u16 = (diff_opaque(20359) as u16);
    let mut diff_step = move || -> u16 {
        diff_acc += (diff_opaque(20359) as u16);
        diff_acc
    };
    println!("{:?}", (0i64..5i64).map(|_| diff_step()).product::<u16>());
}
