// generated by rustscript-differential, seed 20705003522

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u64 {
    fn diff_describe(&self) -> String {
        format!("u64={:?}", self)
    }
}

impl DiffDescribe for Vec<i16> {
    fn diff_describe(&self) -> String {
        format!("Vec[i16]={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let mut v_0_9: u8 = (diff_opaque_u64(127) as u8);
    {
        v_0_9 = v_0_9.rem_euclid(std::mem::replace(&mut v_0_9, (diff_opaque_u64(113) as u8)));
    }
    println!("lang_0_18: {:#0X}", v_0_9);
}
