// generated by rustscript-differential, seed 20679102278

use std::collections::HashSet;

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let lang_value_0: u64 = (diff_opaque_u64(18446744073709551614) as u64);
    let lang_value_2: i64 = ((({ let mut diff_sorted: Vec<i64> = HashSet::<i64>::new().into_iter().collect(); diff_sorted.sort(); diff_sorted }).into_iter().sum::<i64>()) ^ (diff_opaque_i64(-9223372036854775808) as i64)).rem_euclid((lang_value_0 as i64).wrapping_add((diff_opaque_i64(9223372036854775807) as i64).div_euclid((diff_opaque_i64(9223372036854775806) as i64))));
    println!("{:?}", ());
}
