// generated by rustscript-differential, seed 20705102882

use std::collections::{HashMap, HashSet};

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn main() {
    let v_0_4: HashMap<Option<i64>, (u16, String)> = (vec![None::<i64>, Some((diff_opaque_i64(9223372036854775807) as i64))].repeat((diff_opaque_u64(5) as usize)).into_iter().map(|diff_x_0_5: Option<i64>| (diff_x_0_5.clone(), ((diff_opaque_u64(0) as u16), String::from("")))).collect::<HashMap<Option<i64>, (u16, String)>>());
    let v_0_15 = (({ let mut diff_elems: Vec<Option<bool>> = HashSet::<Option<bool>>::new().intersection(&(Vec::<(u16, DiffTrace)>::new().into_iter().map(|diff_x_0_16: (u16, DiffTrace)| None::<bool>).collect::<HashSet<Option<bool>>>())).cloned().collect(); diff_elems.sort(); diff_elems }).into_iter().map(|diff_x_0_17: Option<bool>| (diff_x_0_17.clone(), (!diff_opaque_true()))).collect::<HashMap<Option<bool>, bool>>());
    let v_0_23: u16 = (match (Vec::<(usize, i32)>::new()[(diff_opaque_u64(4) as usize)].clone()) { (diff_b_0_25, diff_b_0_26) => (diff_opaque_u64(0) as u16), });
}
