// generated by rustscript-differential, seed 20740000067

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<u64> {
    fn diff_describe(&self) -> String {
        format!("Vec[u64]={:?}", self)
    }
}

impl DiffDescribe for u32 {
    fn diff_describe(&self) -> String {
        format!("u32={:?}", self)
    }
}

fn main() {
    let mut v_0_15: Vec<DiffTrace> = vec![DiffTrace(1); 2usize];
    let mut diff_i_0_23: usize = 0usize;
    loop {
        diff_i_0_23 += 1usize;
        if diff_i_0_23 > 4usize {
            break;
        }
        v_0_15.retain(|diff_ref| { let diff_r_0_26 = diff_ref.clone(); false });
    }
}
