// generated by rustscript-differential, seed 20704000062

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Default)]
struct DiffS0_0 {
    f0: DiffTrace,
    f1: DiffTrace,
}

impl DiffS0_0 {
    fn diff_m0(&self, diff_a_0_0: u8) -> f32 {
        diff_opaque_f32(1.0f32).to_radians().midpoint(diff_opaque_f32(f32::MAX).round())
    }
    fn diff_m1(&self) -> Self {
        (if (!diff_opaque_true()) { vec![DiffS0_0 { ..Default::default() }] } else { Vec::<DiffS0_0>::new() })[(diff_opaque_u64(2) as usize)].clone()
    }
}

impl DiffDescribe for DiffS0_0 {
    fn diff_describe(&self) -> String {
        format!("DiffS0_0={:?}", self)
    }
}

fn diff_fn_0_17(diff_p_0_18_ref: &u32) -> DiffS0_0 {
    let diff_p_0_18: u32 = diff_p_0_18_ref.clone();
    if ((diff_opaque_i64(0) as i32) < (diff_opaque_i64(2147483647) as i32)) {
        return DiffS0_0 { f0: DiffTrace(4), ..Default::default() };
    }
    DiffS0_0 { f0: DiffTrace(0), f1: DiffTrace(0) }
}

fn main() {
    println!("lang_0_19: {:3?}", diff_fn_0_17(&((diff_opaque_u64(0) as u32))));
}
