// generated by rustscript-differential, seed 20728218855

use std::collections::HashSet;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for f64 {
    fn diff_describe(&self) -> String {
        format!("f64={:?}", self)
    }
}

impl DiffDescribe for i64 {
    fn diff_describe(&self) -> String {
        format!("i64={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
struct DiffS0_0 {
    f0: bool,
}

impl std::fmt::Display for DiffS0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "DiffS0_0 f0={:>2}", self.f0)
    }
}

impl DiffS0_0 {
    fn diff_new(diff_a_0_0: bool) -> Self {
        DiffS0_0 { f0: diff_a_0_0 }
    }
}

impl From<bool> for DiffS0_0 {
    fn from(value: bool) -> Self {
        Self { f0: value }
    }
}

impl DiffDescribe for DiffS0_0 {
    fn diff_describe(&self) -> String {
        format!("DiffS0_0={:?}", self)
    }
}

fn diff_pick_0<T: Clone + std::fmt::Debug>(a: T, b: T, first: bool) -> T {
    if first { a } else { b }
}

fn main() {
    let v_0_1 = DiffS0_0 { f0: diff_opaque_true() };
    let v_0_3: bool = (&[] as &[String]).starts_with(diff_pick_0((Some(vec![String::from("\n")]).unwrap_or_default()).as_slice(), (String::from("0").split_whitespace().map(String::from).collect::<Vec<String>>()).as_slice(), v_0_1.f0));
    let v_0_4 = ((Vec::<Vec<(f64, DiffTrace)>>::new()[(diff_opaque_u64(3) as usize)].clone().into_iter().map(|diff_x_0_5: (f64, DiffTrace)| (diff_opaque_u64(0) as u32)).collect::<HashSet<u32>>()).into_iter().map(|diff_x_0_6: u32| (diff_opaque_u64(0) as usize)).max());
}
