// generated by rustscript-differential, seed 20711000047

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for f32 {
    fn diff_describe(&self) -> String {
        format!("f32={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

#[derive(Debug, Clone, PartialEq, Default)]
struct DiffS0_0 {
    f0: DiffTrace,
}

impl std::fmt::Display for DiffS0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "DiffS0_0 f0={:<?}", self.f0)
    }
}

fn diff_fn_0_7(diff_p_0_8: u8, diff_p_0_9: usize) -> u32 {
    let diff_l_0_10: Result<Vec<f32>, String> = (match (vec![DiffS0_0 { f0: DiffTrace(5) }, DiffS0_0 { f0: DiffTrace(6) }][(diff_opaque_u64(0) as usize)].clone()) { DiffS0_0 { .. } => vec![Ok::<Vec<f32>, String>(Vec::<f32>::new()), Ok::<Vec<f32>, String>(vec![diff_opaque_f32(f32::INFINITY); 2usize]), Err::<Vec<f32>, String>(String::from("true"))][(diff_opaque_u64(4) as usize)].clone(), });
    (diff_opaque_u64(0) as u32)
}

fn main() {
    println!("lang_0_13: {0:+?}", diff_fn_0_7((diff_opaque_u64(0) as u8), (diff_opaque_u64(0) as usize)));
}
