// generated by rustscript-differential, seed 77104527

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i16 {
    fn diff_describe(&self) -> String {
        format!("i16={:?}", self)
    }
}

impl DiffDescribe for u16 {
    fn diff_describe(&self) -> String {
        format!("u16={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_pick_0<T: Clone + std::fmt::Debug>(a: T, b: T, first: bool) -> T {
    if first { a } else { b }
}

fn diff_fn_0_9(diff_p_0_10_ref: &DiffTrace, diff_p_0_11: String) -> Result<usize, usize> {
    let diff_p_0_10: DiffTrace = diff_p_0_10_ref.clone();
    Ok::<usize, usize>((diff_opaque_u64(0) as usize))
}

fn main() {
    let v_0_8: Result<usize, usize> = diff_fn_0_9(&(DiffTrace(0)), format!("{:?}", vec![DiffTrace(3)].iter().collect::<std::collections::BTreeSet<_>>()));
}
