// generated by rustscript-differential, seed 500310

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for char {
    fn diff_describe(&self) -> String {
        format!("char={:?}", self)
    }
}

fn main() {
    let v_0_0 = (&(Vec::<Vec<i32>>::new())[2usize..]).last().cloned().unwrap_or_default();
}
