// generated by rustscript-differential, seed 1303027

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<i32> {
    fn diff_describe(&self) -> String {
        format!("Vec[i32]={:?}", self)
    }
}

fn diff_opaque_true() -> bool {
    true
}

fn diff_pick_0<T: Clone + std::fmt::Debug>(a: T, b: T, first: bool) -> T {
    if first { a } else { b }
}

fn main() {
    let v_0_14: Vec<DiffTrace> = diff_pick_0((vec![vec![DiffTrace(1), DiffTrace(2)]].concat()).as_slice(), (vec![DiffTrace(3)].into_iter().rev().collect::<Vec<DiffTrace>>()).as_slice(), (!diff_opaque_true())).iter().rev().cloned().collect::<Vec<DiffTrace>>();
}
