// generated by rustscript-differential, seed 500274

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<i16> {
    fn diff_describe(&self) -> String {
        format!("Vec[i16]={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    println!("lang_0_16: {:>12?}", ({ let mut diff_r = vec![(diff_opaque_u64(9223372036854775808) as usize), (diff_opaque_u64(18446744073709551615) as usize)]; diff_r.sort_by_key(|x| std::cmp::Reverse(x.clone())); diff_r }));
}
