// generated by rustscript-differential, seed 81202693

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i64 {
    fn diff_describe(&self) -> String {
        format!("i64={:?}", self)
    }
}

impl DiffDescribe for char {
    fn diff_describe(&self) -> String {
        format!("char={:?}", self)
    }
}

fn main() {
    println!("lang_0_35: {:<+#}", (!String::from("").strip_prefix("a\nb\nc").map(String::from).as_deref().map_or(0, |s| s.len())));
}
