// generated by rustscript-differential, seed 20720000213

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<i32> {
    fn diff_describe(&self) -> String {
        format!("Vec[i32]={:?}", self)
    }
}

impl DiffDescribe for usize {
    fn diff_describe(&self) -> String {
        format!("usize={:?}", self)
    }
}

fn main() {
    let mut v_0_1: Vec<DiffTrace> = Vec::<DiffTrace>::new();
    v_0_1[1usize] = DiffTrace(0);
}
