// generated by rustscript-differential, seed 500225

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let v_0_6 = (&("")[2usize..3usize]).repeat((diff_opaque_u64(5) as usize));
}
