// generated by rustscript-differential, seed 500337

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let v_0_3: Option<&str> = "".split((&("")[1usize..])).nth((diff_opaque_u64(1) as usize));
}
