// generated by rustscript-differential, seed 9029

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffS0_0 {
    f0: i64,
}

impl DiffS0_0 {
    fn diff_new(diff_a_0_0: i64) -> Self {
        DiffS0_0 { f0: diff_a_0_0 }
    }
}

fn main() {
    println!("lang_0_28: {0:?} {0:?}", vec![DiffS0_0 { f0: (diff_opaque_i64(9223372036854775806) as i64) }, DiffS0_0 { f0: (diff_opaque_i64(9223372036854775807) as i64) }].iter().max().cloned().unwrap_or(DiffS0_0 { f0: (diff_opaque_i64(0) as i64) }));
    println!("lang_0_31: {:+E}", diff_opaque_f32(0.0f32).clamp(diff_opaque_f32(0.0f32), diff_opaque_f32(f32::INFINITY).rem_euclid(diff_opaque_f32(f32::EPSILON))));
}
