// generated by rustscript-differential, seed 20720000409

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for bool {
    fn diff_describe(&self) -> String {
        format!("bool={:?}", self)
    }
}

impl DiffDescribe for Vec<u16> {
    fn diff_describe(&self) -> String {
        format!("Vec[u16]={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffS0_0 {
    f0: i8,
    f1: DiffTrace,
    f2: u32,
}

impl std::fmt::Display for DiffS0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.pad(&format!("DiffS0_0 f0={:0E} f1={:?} f2={:#5}", self.f0, self.f1, self.f2))
    }
}

impl DiffS0_0 {
    fn diff_m0(&self) -> bool {
        (!diff_opaque_true())
    }
    fn diff_new(diff_a_0_0: i8, diff_a_0_1: DiffTrace) -> Self {
        DiffS0_0 { f0: diff_a_0_0, f1: diff_a_0_1, f2: (diff_opaque_u64(0) as u32) }
    }
}

impl DiffDescribe for DiffS0_0 {
    fn diff_describe(&self) -> String {
        format!("DiffS0_0={:?}", self)
    }
}

fn diff_fn_0_32() -> DiffS0_0 {
    DiffS0_0 { f0: (diff_opaque_i64(0) as i8), f1: DiffTrace(0), f2: ((diff_opaque_u64(1372733154) as u32) * (diff_opaque_u64(4294967294) as u32)) }
}

fn main() {
    println!("lang_0_36: {:?}", diff_fn_0_32());
}
