// generated by rustscript-differential, seed 5223

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<i32> {
    fn diff_describe(&self) -> String {
        format!("Vec[i32]={:?}", self)
    }
}

impl DiffDescribe for Vec<f64> {
    fn diff_describe(&self) -> String {
        format!("Vec[f64]={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let v_0_6: u16 = (((-9i64..-6i64).map(|diff_x_0_7: i64| (diff_opaque_u64(65535) as u16)).collect::<Vec<u16>>()).into_iter().sum());
    println!("lang_0_65: {0:?}", (diff_opaque_i64(0) as i8));
    println!("lang_0_70: {:?}", (match (((diff_opaque_i64(-127) as i8) - (diff_opaque_i64(126) as i8))) { _ => Vec::<f64>::new(), }));
}
