// generated by rustscript-differential, seed 20750000427

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for i8 {
    fn diff_describe(&self) -> String {
        format!("i8={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

const DIFF_C0_0: bool = true;

fn diff_fn_0_16(diff_p_0_17_ref: &usize) -> DiffTrace {
    let diff_p_0_17: usize = diff_p_0_17_ref.clone();
    Some(DiffTrace(7)).unwrap_or(vec![DiffTrace(8); 2usize][(diff_opaque_u64(2) as usize)].clone())
}

fn main() {
    if (if diff_opaque_true() { DIFF_C0_0 } else { false }) {
        println!("lang_0_19: {:?}", diff_fn_0_16(&((diff_opaque_u64(0) as usize))));
    } else {
    }
}
