// generated by rustscript-differential, seed 483902633582

use std::collections::HashSet;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<u32> {
    fn diff_describe(&self) -> String {
        format!("Vec[u32]={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_char(value: char) -> char {
    value
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffS0_2 {
    f0: usize,
    f1: DiffTrace,
    f2: DiffTrace,
}

impl std::fmt::Display for DiffS0_2 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.pad(&format!("DiffS0_2 f0={:*^011X} f1={:?} f2={:#2?}", self.f0, self.f1, self.f2))
    }
}

impl DiffS0_2 {
    fn diff_new(diff_a_0_1: usize, diff_a_0_2: DiffTrace) -> Self {
        DiffS0_2 { f0: diff_a_0_1, f1: diff_a_0_2, f2: vec![DiffTrace(1)][(diff_opaque_u64(2) as usize)].clone() }
    }
}

impl From<usize> for DiffS0_2 {
    fn from(value: usize) -> Self {
        Self { f0: value, ..Default::default() }
    }
}

fn main() {
    let v_0_3: char = diff_opaque_char('a');
    let v_0_3: HashSet<String> = HashSet::<String>::new();
    let mut v_0_3 = DiffS0_2 { f0: (diff_opaque_u64(0) as usize), f1: DiffTrace(0), f2: DiffTrace(0) };
    v_0_3 = DiffS0_2::diff_new((diff_opaque_u64(0) as usize), DiffTrace(0));
}
