// generated by rustscript-differential, seed 483902539158

use std::collections::HashSet;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for char {
    fn diff_describe(&self) -> String {
        format!("char={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let v_0_5: HashSet<u8> = ((18i64..19i64).map(|diff_x_0_6| (vec![DiffTrace(1), DiffTrace(2)].into_iter().map(|diff_x_0_7: DiffTrace| (diff_opaque_u64(0) as u8)).fold((match (vec![DiffTrace(3)]).as_slice() { _ => (diff_opaque_u64(0) as u8), }), |diff_x_0_8, diff_x_0_9| Vec::<u8>::new()[(diff_opaque_u64(0) as usize)].clone()))).collect::<HashSet<u8>>());
}
