// generated by rustscript-differential, seed 20719002658

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<usize> {
    fn diff_describe(&self) -> String {
        format!("Vec[usize]={:?}", self)
    }
}

impl DiffDescribe for Vec<String> {
    fn diff_describe(&self) -> String {
        format!("Vec[String]={:?}", self)
    }
}

fn diff_opaque_i64(value: i64) -> i64 {
    value
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f32(value: f32) -> f32 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Default)]
struct DiffS0_0 {
    f0: bool,
    f1: f32,
}

impl std::fmt::Display for DiffS0_0 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "DiffS0_0 f0={:?} f1={:?}", self.f0, self.f1)
    }
}

impl DiffS0_0 {
    fn diff_m0(&self, diff_a_0_0: i32) -> Self {
        Some(DiffS0_0 { f0: diff_opaque_true(), f1: self.f1 }).unwrap_or(DiffS0_0 { f0: self.f0, f1: self.f1 })
    }
    fn diff_m1(&self) -> i16 {
        ((diff_opaque_i64(-21783) as i16) % (diff_opaque_i64(-1) as i16)).div_euclid((diff_opaque_i64(16384) as i16))
    }
}

#[derive(Debug, Clone, PartialEq, Default)]
struct DiffS0_2 {
    f0: DiffTrace,
    f1: DiffS0_0,
    f2: DiffTrace,
}

impl std::fmt::Display for DiffS0_2 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "DiffS0_2 f0={:?} f1={:~<} f2={:?}", self.f0, self.f1, self.f2)
    }
}

impl DiffS0_2 {
    fn diff_m0(&self, diff_a_0_1: u32) -> usize {
        String::from("1.5").trim_end().to_string().split(String::from("  padded  ").as_str()).count()
    }
    fn diff_m1(&self, diff_a_0_2: i16) -> u32 {
        (diff_opaque_u64(4294967295) as u32)
    }
}

fn diff_pick_0<T: Clone + std::fmt::Debug>(a: T, b: T, first: bool) -> T {
    if first { a } else { b }
}

fn diff_fn_0_5(diff_p_0_6_ref: &f64) -> Option<u32> {
    let diff_p_0_6: f64 = diff_p_0_6_ref.clone();
    let diff_l_0_7: DiffS0_2 = diff_pick_0(DiffS0_2 { f0: DiffTrace(1), f1: DiffS0_0 { f0: diff_opaque_true(), f1: diff_opaque_f32(0.5f32) }, f2: DiffTrace(2) }, None::<DiffS0_2>.unwrap_or_default(), (None::<bool>?));
    None::<u32>
}

fn main() {
    let v_0_4 = diff_fn_0_5(&{ diff_opaque_f64(0.0f64) });
}
