// generated by rustscript-differential, seed 12079

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<i64> {
    fn diff_describe(&self) -> String {
        format!("Vec[i64]={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_true() -> bool {
    true
}

fn main() {
    let (v_0_0, v_0_1, v_0_2) = (!diff_opaque_true()).then_some(((diff_opaque_u64(0) as u16), (diff_opaque_u64(0) as usize), (!diff_opaque_true()))).unwrap_or_default();
    println!("lang_0_17: {0:4}", (v_0_1 / (diff_opaque_u64(0) as usize)));
}
