// generated by rustscript-differential, seed 500150

use std::collections::HashSet;

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u64 {
    fn diff_describe(&self) -> String {
        format!("u64={:?}", self)
    }
}

impl DiffDescribe for Vec<f64> {
    fn diff_describe(&self) -> String {
        format!("Vec[f64]={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_write_0_13(diff_target: &mut String) {
    let diff_cur: String = diff_target.clone();
    *diff_target = ({ let mut diff_m = std::collections::BTreeMap::new(); for diff_x in vec![(diff_opaque_u64(0) as usize)] { *diff_m.entry(diff_x).or_insert(0usize) += 1; } format!("{:?}", diff_m) });
}

fn main() {
    let mut v_0_1 = String::from("");
    let mut v_0_8: HashSet<usize> = HashSet::<usize>::new();
    diff_write_0_13(&mut v_0_1);
    v_0_8 = Err::<HashSet<usize>, String>(String::from("")).expect("differential expect");
}
