// generated by rustscript-differential, seed 483902630363

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for String {
    fn diff_describe(&self) -> String {
        format!("String={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn diff_opaque_f64(value: f64) -> f64 {
    value
}

fn main() {
    let v_0_3 = (diff_opaque_u64(761893548003126452) as usize).is_multiple_of((diff_opaque_u64(9223372036854775807) as usize)).then_some((diff_opaque_f64(f64::NAN), DiffTrace(1))).unwrap_or_default();
}
