// generated by rustscript-differential, seed 500270

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for f64 {
    fn diff_describe(&self) -> String {
        format!("f64={:?}", self)
    }
}

impl DiffDescribe for i8 {
    fn diff_describe(&self) -> String {
        format!("i8={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    println!("lang_0_34: {0:?} {0:?}", ({ let mut diff_r = (({ let mut diff_r = Vec::<DiffTrace>::new(); let diff_d = DiffTrace(1); diff_r.insert((diff_opaque_u64(4) as usize), diff_d); diff_r }).into_iter().min()); let diff_d = DiffTrace(2); diff_r.get_or_insert_with(|| diff_d).clone() }));
}
