// generated by rustscript-differential, seed 20705000910

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for usize {
    fn diff_describe(&self) -> String {
        format!("usize={:?}", self)
    }
}

impl DiffDescribe for Vec<f64> {
    fn diff_describe(&self) -> String {
        format!("Vec[f64]={:?}", self)
    }
}

impl DiffDescribe for Vec<usize> {
    fn diff_describe(&self) -> String {
        format!("Vec[usize]={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

fn main() {
    let mut v_0_0 = Vec::<Vec<usize>>::new();
    let v_0_1: Vec<Vec<usize>> = std::mem::replace(&mut v_0_0, vec![Vec::<usize>::new(); 3usize]);
    v_0_0[0usize].push((diff_opaque_u64(0) as usize));
    println!("lang_0_10: {:?}", v_0_0);
    let v_1_9: DiffTrace = DiffTrace(0);
}
