// generated by rustscript-differential, seed 20721203971

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for u16 {
    fn diff_describe(&self) -> String {
        format!("u16={:?}", self)
    }
}

fn main() {
    println!("lang_0_48: {:?}", vec![DiffTrace(9); 2usize].into_iter().zip(Vec::<DiffTrace>::new()).collect::<Vec<(DiffTrace, DiffTrace)>>());
}
