// generated by rustscript-differential, seed 20719204179

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

fn main() {
    let v_0_2: Vec<Option<String>> = (Vec::<DiffTrace>::new().into_iter().zip(vec![DiffTrace(2)]).collect::<Vec<(DiffTrace, DiffTrace)>>().into_iter().map(|diff_x_0_3| None::<String>).collect::<Vec<Option<String>>>());
}
