// generated by rustscript-differential, seed 700642

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffTrace(i64);

impl Drop for DiffTrace {
    fn drop(&mut self) {
        println!("drop {}", self.0);
    }
}

trait DiffDescribe {
    fn diff_describe(&self) -> String;
}

impl DiffDescribe for Vec<i32> {
    fn diff_describe(&self) -> String {
        format!("Vec[i32]={:?}", self)
    }
}

impl DiffDescribe for char {
    fn diff_describe(&self) -> String {
        format!("char={:?}", self)
    }
}

fn diff_opaque_u64(value: u64) -> u64 {
    value
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Default)]
struct DiffS0_0 {
    f0: DiffTrace,
}

impl DiffS0_0 {
    fn diff_m0(&self) -> Self {
        DiffS0_0 { f0: DiffTrace(1) }
    }
    fn diff_m1(&self) -> String {
        format!("{:?}", String::from("99999999999999999999").as_bytes())
    }
}

impl DiffDescribe for DiffS0_0 {
    fn diff_describe(&self) -> String {
        format!("DiffS0_0={:?}", self)
    }
}

fn main() {
    println!("lang_0_42: {:?}", (({ let diff_r = Vec::<DiffS0_0>::new(); let diff_d = vec![DiffS0_0 { f0: DiffTrace(0) }; 1usize]; let (mut diff_a, diff_b) = diff_r.into_iter().zip(diff_d).unzip::<DiffS0_0, DiffS0_0, Vec<DiffS0_0>, Vec<DiffS0_0>>(); diff_a.extend(diff_b); diff_a }).into_iter().map(|diff_x_0_41: DiffS0_0| (diff_opaque_u64(0) as usize)).sum::<usize>()));
}
