// generated by rustscript-differential, seed 900005

fn diff_opaque(x: i64) -> i64 {
    x
}

fn main() {
    {
        let flow_0_value_0: f64 = (0.0f64 - f64::MIN_POSITIVE);
        let flow_0_value_1: Vec<i64> = { let mut generated_values = Vec::<i64>::new(); generated_values.push((|closure_arg_7: i64| (diff_opaque(closure_arg_7) * diff_opaque(closure_arg_7)))(((-1e300f64) as i64))); generated_values };
        println!("generated-dataflow-0:{:?}", (flow_0_value_0, flow_0_value_1));
    }
    println!("{:?}", ());
}
