// generated by rustscript-differential, seed 12009043

use std::path::PathBuf;

enum GeneratedState {
    Idle,
    Named(String),
    Located { path: PathBuf, values: Vec<i64> },
}

fn diff_opaque(x: i64) -> i64 {
    x
}

fn adjust(value: i64, flag: bool) -> i64 {
    if flag {
        value + 2i64
    } else {
        value - 2i64
    }
}

fn main() {
    let value_0: i64 = adjust(20i64, false);
    let mut value_1: bool = !((true || false));
    let mut value_2: String = if false { format!("{}{}", String::from("script"), String::from("script")) } else { if false { String::from("script") } else { String::from("") } };
    let mut value_3: bool = !((value_0 < -1i64));
    let mut value_4: bool = if (value_0 < value_0) { if value_3 { value_1 } else { value_3 } } else { (value_3 && false) };
    let value_5: i64 = (adjust(28i64, value_1)).saturating_mul(-1i64);
    let value_6: i64 = adjust((value_0).saturating_add(value_0), (6i64 == 35i64));
    value_3 = true;
    value_4 = (value_0 < (value_0).saturating_mul(-3i64));
    value_1 = ((false && true) && (value_5 < -37i64));
    value_2 = (if false { value_2.clone() } else { value_2.clone() }).repeat(1);
    {
        let enum_state = GeneratedState::Named("λ".to_string());
        let enum_bias = 8i64;
        let enum_sum = |values: Vec<i64>| {
            values
                .iter()
                .copied()
                .fold(enum_bias, |total, value| total.saturating_add(value))
        };
        let enum_label = match enum_state {
            GeneratedState::Idle => "idle".to_string(),
            GeneratedState::Named(name) if name.contains("rust") => {
                format!("matched:{}", name.to_uppercase())
            }
            GeneratedState::Named(name) => format!("named:{name}"),
            GeneratedState::Located { path, values } => {
                let total = enum_sum(values);
                format!("located:{}:{total}", path.display())
            }
        };
        println!("enum:{enum_label}");
    }
    {
        let nested_outer_bias = 7i64;
        let nested_make = |left: i64| {
            let captured = left.saturating_add(nested_outer_bias);
            move |right: i64| {
                captured
                    .saturating_mul(right)
                    .saturating_add(0i64)
            }
        };
        let nested_operation = nested_make(5i64);
        let nested_first = nested_operation(4i64);
        let nested_second = nested_operation(-2i64);
        println!("closure-nested:{nested_first}:{nested_second}");
    }
    {
        let move_prefix = "".to_string();
        let move_suffixes: Vec<String> = vec![" a ".to_string(), "script ".to_string(), " a ".to_string(), "λ".to_string()];
        let decorate = move |(index, suffix): (usize, String)| {
            format!(
                "{}:{index}:{}",
                move_prefix.to_uppercase(),
                suffix.trim()
            )
        };
        let move_output: Vec<String> = move_suffixes
            .into_iter()
            .enumerate()
            .map(decorate)
            .collect();
        println!("closure-move:{move_output:?}");
    }
    {
        let flow_0_value_0: Option<i64> = None::<i64>;
        let flow_0_value_1: bool = ((256i64) < (((-17i64 as i32) as i64)));
        let flow_0_value_2: Vec<i64> = Vec::<i64>::new();
        let flow_0_value_3: String = if if (true || false) { ((-0.0f64) < (3.141592653589793f64)) } else { ((44i64) < (-47i64)) } { format!("{:?}", (f64::NAN + 1.7976931348623157e308f64)) } else { format!("{}{}", "a".to_string(), format!("{}", -20i64)) };
        let flow_0_value_4: Vec<i64> = { let mut generated_values = { let mut generated_values = vec![-20i64]; generated_values.push(-27i64); generated_values }; generated_values.push((9i64).saturating_mul(11i64)); generated_values };
        let flow_0_value_5: String = (|closure_arg_0: i64| format!("{:?}", ((10.25f64 / -2.5f64) / (|closure_arg_1: i64| 1.7976931348623157e308f64)(closure_arg_0))))((((diff_opaque(((((-2147483648i64 as u32) as i64) as usize) as i64)) as i32) % (diff_opaque((((-2.5f64 - -1e300f64)) as i64)) as i32)) as i64));
        let mut flow_0_value_6: Vec<i64> = vec![38i64, (Some((|option_closure_2: i64| 43i64)(-44i64))).unwrap_or(if flow_0_value_1 { -23i64 } else { 4294967295i64 }), ({ let mut generated_values = flow_0_value_4.clone(); generated_values.reverse(); generated_values })[1usize], match Some(-4611686018427387904i64) { Some(matched_3) => if flow_0_value_1 { matched_3 } else { matched_3 }, None => (flow_0_value_0).unwrap() }, ((vec![6i64, -20i64, -15i64, -15i64, -20i64]).into_iter().filter(|generated_ref| { let filter_value_4 = *generated_ref; flow_0_value_1 }).collect::<Vec<i64>>()).get(4usize).copied().unwrap_or((255i64).saturating_sub(-2147483648i64))];
        let flow_0_value_7: Vec<i64> = ({ let mut generated_values = { let mut generated_values = { let mut generated_values = flow_0_value_4.clone(); generated_values.reverse(); generated_values }; generated_values.push(((-23i64 as u32) as i64)); generated_values }; generated_values.push(((vec![2i64, -3i64]).into_iter().map(|map_value_6: i64| 4294967295i64).collect::<Vec<i64>>())[6usize]); generated_values }).into_iter().map(|map_value_5: i64| ((diff_opaque(map_value_5) - diff_opaque((((diff_opaque(map_value_5) as u32) + (diff_opaque(25i64) as u32)) as i64)))).saturating_sub(((((map_value_5 as u8) as i64) as u32) as i64))).collect::<Vec<i64>>();
        let mut flow_0_value_8: i64 = -2147483648i64;
        let flow_0_value_9: f64 = (((3.141592653589793f64 * 0.5f64) * (|closure_arg_7: i64| f64::NEG_INFINITY)(-37i64)) * (match flow_0_value_0 { Some(matched_8) => f64::NAN, None => f64::INFINITY } / (f64::INFINITY / 9007199254740993.0f64)));
        flow_0_value_8 = flow_0_value_8;
        if ((((flow_0_value_9 / flow_0_value_9) - ((flow_0_value_8) as f64))) == ((|closure_arg_9: i64| (flow_0_value_9 + flow_0_value_9))(if false { flow_0_value_8 } else { -1099511627776i64 }))) {
            flow_0_value_6 = Vec::<i64>::new();
        } else {
            flow_0_value_6 = ({ let mut generated_values = { let mut generated_values = flow_0_value_2.clone(); generated_values.push(1099511627776i64); generated_values }; generated_values.reverse(); generated_values }).into_iter().filter(|generated_ref| { let filter_value_10 = *generated_ref; ((match Some(13i64) { Some(matched_11) => matched_11, None => filter_value_10 }) < (((flow_0_value_9) as i64))) }).collect::<Vec<i64>>();
        }
        println!("generated-dataflow-0:{:?}", (flow_0_value_0, flow_0_value_1, flow_0_value_2, flow_0_value_3, flow_0_value_4, flow_0_value_5, flow_0_value_6, flow_0_value_7, flow_0_value_8, flow_0_value_9));
    }
    {
        let closure_scale_1 = 0i64;
        let closure_bias_1 = 5i64;
        let closure_input_1: Vec<i64> = vec![11i64, -13i64, -5i64, 18i64, 19i64, 6i64];
        let closure_factory_1 = |mut closure_state_1: i64| {
            move |closure_item_1: i64| {
                closure_state_1 = (closure_state_1).saturating_add(((closure_item_1).saturating_mul(closure_scale_1)).saturating_add((({ let mut generated_values = (vec![18i64, -6i64, -4i64]).into_iter().filter(|generated_ref| { let filter_value_15001 = *generated_ref; true }).collect::<Vec<i64>>(); generated_values.push(((f64::NEG_INFINITY) as i64)); generated_values }).into_iter().map(|map_value_15000: i64| (diff_opaque(closure_state_1) * diff_opaque(((f64::NAN) as i64)))).collect::<Vec<i64>>()).get(2usize).copied().unwrap_or((|closure_arg_15002: i64| ((diff_opaque(closure_bias_1) / diff_opaque(closure_scale_1))).saturating_sub((diff_opaque(closure_item_1) + diff_opaque(-26i64))))(((|closure_arg_15003: i64| None::<i64>)(closure_state_1)).unwrap()))));
                closure_state_1
            }
        };
        let mut closure_operation_1 = closure_factory_1(20i64);
        let closure_output_1: Vec<i64> = closure_input_1
            .into_iter()
            .map(|closure_item_1| closure_operation_1(closure_item_1))
            .collect();
        println!("generated-closure-1:{closure_output_1:?}");
    }
    {
        let flow_2_value_0: bool = if (((|closure_arg_20000: i64| (5e-324f64 / 2.5f64))(1i64)) == (match if true { Some(6i64) } else { Some(7i64) } { Some(matched_20001) => match None::<i64> { Some(matched_20002) => 9007199254740993.0f64, None => 2.5f64 }, None => (0.30000000000000004f64 * 1e300f64) })) { (((|closure_arg_20004: i64| Some(23i64))(9i64)).filter(|generated_ref| { let option_filter_20003 = *generated_ref; ((0.1f64) == (1e300f64)) })).is_some() } else { (None::<i64>).is_some() };
        let flow_2_value_1: Vec<i64> = { let mut generated_values = vec![(|closure_arg_20005: i64| closure_arg_20005)(-28i64), -1099511627776i64, ((-8i64 as usize) as i64), 48i64, (|closure_arg_20006: i64| closure_arg_20006)(-2147483648i64)]; generated_values.reverse(); generated_values };
        let mut flow_2_value_2: Vec<i64> = if ((26i64) == (0i64)) { (|closure_arg_20007: i64| if (None::<i64>).is_some() { (vec![-14i64, -9i64, 20i64, 13i64, 16i64]).into_iter().filter(|generated_ref| { let filter_value_20008 = *generated_ref; flow_2_value_0 }).collect::<Vec<i64>>() } else { { let mut generated_values = flow_2_value_1.clone(); generated_values.push(36i64); generated_values } })(-12i64) } else { vec![15i64, -12i64] };
        let flow_2_value_3: i64 = if (((|closure_arg_20009: i64| f64::EPSILON)(2147483647i64)) == ((0.1f64 + -1.0f64))) { i64::MIN } else { (None::<i64>).unwrap_or(-4611686018427387904i64) };
        let flow_2_value_4: bool = ((((3.141592653589793f64 * f64::EPSILON)) == ((|closure_arg_20010: i64| 1.0f64)(flow_2_value_3))) && ((((flow_2_value_3 as i16) as i64)) == (((1.5f64) as i64))));
        let mut flow_2_value_5: Option<i64> = Some((diff_opaque(flow_2_value_3) - diff_opaque(flow_2_value_3)));
        let mut flow_2_value_6: String = format!("{}{}", "line\nbreak".to_string(), format!("{}", (flow_2_value_3).saturating_add(-28i64)));
        let mut flow_2_value_7: Option<i64> = None::<i64>;
        flow_2_value_2 = Vec::<i64>::new();
        flow_2_value_6 = if ((if false { 1.0f64 } else { 0.5f64 }) == ((f64::NEG_INFINITY / f64::NEG_INFINITY))) { format!("{:E}", (1.5f64 - -2.5f64)) } else { format!("{}{}", if flow_2_value_0 { "script".to_string() } else { flow_2_value_6.clone() }, format!("{:<8}", -23i64)) };
        if ((((flow_2_value_3) as f64)) < ((1e300f64 + 0.1f64))) {
            flow_2_value_5 = if ((flow_2_value_3) < (flow_2_value_3)) { None::<i64> } else { (|closure_arg_20011: i64| flow_2_value_7)(flow_2_value_3) };
        } else {
            flow_2_value_5 = (None::<i64>).filter(|generated_ref| { let option_filter_20012 = *generated_ref; false });
        }
        flow_2_value_5 = if (flow_2_value_7).is_some() { (Some(-24i64)).filter(|generated_ref| { let option_filter_20013 = *generated_ref; match flow_2_value_7 { Some(matched_20014) => flow_2_value_0, None => true } }) } else { (|closure_arg_20015: i64| Some((|option_closure_20016: i64| -15i64)(closure_arg_20015)))((flow_2_value_3).saturating_add(-35i64)) };
        if if (((|closure_arg_20017: i64| 44i64)(flow_2_value_3)) == ((diff_opaque(flow_2_value_3) - diff_opaque(255i64)))) { if ((1e-300f64) < (0.30000000000000004f64)) { (true || flow_2_value_4) } else { match Some(12i64) { Some(matched_20018) => flow_2_value_0, None => flow_2_value_4 } } } else { (if flow_2_value_4 { Some(-16i64) } else { Some(24i64) }).is_some() } {
            flow_2_value_2 = { let mut generated_values = { let mut generated_values = vec![12i64, -7i64]; generated_values.reverse(); generated_values }; generated_values.reverse(); generated_values };
        } else {
            flow_2_value_2 = if (!(true) && flow_2_value_0) { { let mut generated_values = (Vec::<i64>::new()).into_iter().map(|map_value_20019: i64| -16i64).collect::<Vec<i64>>(); generated_values.reverse(); generated_values } } else { { let mut generated_values = vec![i64::MIN, 2147483647i64, -8i64, flow_2_value_3]; generated_values.push((diff_opaque(flow_2_value_3) + diff_opaque(4294967295i64))); generated_values } };
        }
        flow_2_value_7 = (Some((|option_closure_20021: i64| (|closure_arg_20022: i64| (flow_2_value_1.clone()).len() as i64)((diff_opaque(flow_2_value_3) - diff_opaque(flow_2_value_3))))((diff_opaque(flow_2_value_3) * diff_opaque((diff_opaque(flow_2_value_3) - diff_opaque(flow_2_value_3))))))).map(|option_map_20020: i64| ((((|closure_arg_20023: i64| flow_2_value_1.clone())(flow_2_value_3)).get(2usize).copied().unwrap_or((Some(-29i64)).unwrap()) as usize) as i64));
        println!("generated-dataflow-2:{:?}", (flow_2_value_0, flow_2_value_1, flow_2_value_2, flow_2_value_3, flow_2_value_4, flow_2_value_5, flow_2_value_6, flow_2_value_7));
    }
    {
        let iterator_values_0: Vec<i64> = vec![17i64, 3i64, -11i64];
        let iterator_selected_0: Vec<i64> = iterator_values_0
            .into_iter()
            .enumerate()
            .filter_map(|(index, value)| {
                if index % 2usize == 1usize {
                    Some(value.saturating_add(index as i64))
                } else {
                    None
                }
            })
            .take(0usize)
            .collect();
        let mut iterator_index_0 = 0usize;
        let mut iterator_total_0 = 0i64;
        loop {
            if iterator_index_0 >= iterator_selected_0.len() {
                break;
            }
            let iterator_value_0 = iterator_selected_0[iterator_index_0];
            iterator_index_0 = iterator_index_0.saturating_add(1usize);
            if false && iterator_value_0 < 0i64 {
                continue;
            }
            iterator_total_0 = iterator_total_0.saturating_add(iterator_value_0);
        }
        println!(
            "semantic-iterator-0:{iterator_selected_0:?}:{iterator_total_0}"
        );
    }
    {
        let method_text_0: String = "rust script".to_string();
        let method_values_0: Vec<i64> = vec![8i64];
        println!("method-0-vec-is-empty:{:?}", method_values_0.is_empty());
        println!("method-0-vec-all:{:?}", method_values_0.iter().all(|&value| value < 14i64));
        println!("method-0-vec-any:{:?}", method_values_0.iter().any(|&value| value > 14i64));
        println!("method-0-vec-rev:{:?}", method_values_0.iter().rev().copied().collect::<Vec<i64>>());
        println!("method-0-str-trim-end:{:?}", method_text_0.trim_end());
        println!("method-0-vec-max:{:?}", method_values_0.iter().max().copied());
    }
    println!("{:?}", (value_0, value_1, value_2, value_3, value_4, value_5, value_6));
}
