// generated by rustscript-differential, seed 900014

fn diff_opaque(x: i64) -> i64 {
    x
}

fn main() {
    {
        let flow_0_value_0: Vec<i64> = Vec::<i64>::new();
        let flow_0_value_1: Option<i64> = None::<i64>;
        let mut flow_0_value_2: i64 = 9223372036854775807i64;
        let flow_0_value_3: String = "".to_string();
        let flow_0_value_4: bool = (((((diff_opaque((Vec::<i64>::new()).get(4usize).copied().unwrap_or(flow_0_value_2)) as u8) * (diff_opaque(-45i64) as u8)) as i64)) == (0i64));
        println!("generated-dataflow-0:{:?}", (flow_0_value_0, flow_0_value_1, flow_0_value_2, flow_0_value_3, flow_0_value_4));
    }
    {
        let mut flow_1_value_0: Option<i64> = None::<i64>;
        let flow_1_value_1: i64 = 0i64;
        let flow_1_value_2: i64 = 0i64;
        let flow_1_value_3: bool = false;
        let mut flow_1_value_4: String = "".to_string();
        let flow_1_value_5: Vec<i64> = (vec![0i64]).into_iter().filter(|generated_ref| { let filter_value_10002 = *generated_ref; (((Vec::<i64>::new())[6usize]) == (0i64)) }).collect::<Vec<i64>>();
        println!("generated-dataflow-1:{:?}", (flow_1_value_0, flow_1_value_1, flow_1_value_2, flow_1_value_3, flow_1_value_4, flow_1_value_5));
    }
    println!("{:?}", ());
}
