//! A generated program: its seed, the blocks that make up `fn main`, and the
//! structured mutation it came from, if any.

use std::collections::BTreeSet;

use serde::{Deserialize, Serialize};

use crate::lang::Block;
use crate::lang::user::{DESCRIBE_TRAIT, render_describe_impl};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub enum MutationOperation {
    /// A same-typed subtree from the donor replaced a subtree here.
    Splice,
    /// The blocks were rendered in reverse order.
    BlockOrder,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct MutationOrigin {
    pub parent_seed: u64,
    pub donor_seed: u64,
    pub operations: Vec<MutationOperation>,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct Program {
    pub seed: u64,
    pub blocks: Vec<Block>,
    #[serde(default)]
    pub mutation: Option<MutationOrigin>,
}

impl Program {
    pub fn render(&self) -> String {
        let mut body = String::new();
        for block in &self.blocks {
            body.push_str(&block.render());
        }
        let mut items = String::new();
        if self.blocks.iter().any(Block::uses_describe) {
            items.push_str(DESCRIBE_TRAIT);
            let mut seen: BTreeSet<String> = BTreeSet::new();
            for ty in self.blocks.iter().flat_map(|block| block.describes.iter()) {
                if seen.insert(ty.rust()) {
                    items.push_str(&render_describe_impl(ty));
                }
            }
        }
        let mut helpers = BTreeSet::new();
        for block in &self.blocks {
            helpers.extend(block.helpers());
        }
        for helper in helpers {
            items.push_str(helper.definition());
        }
        for block in &self.blocks {
            items.push_str(&block.render_items());
        }

        let mut source = format!(
            "// generated by rustscript-differential, seed {}\n\n",
            self.seed
        );
        if let Some(origin) = &self.mutation {
            source.push_str(&format!(
                "// structured mutation from seeds {} and {} using {:?}\n\n",
                origin.parent_seed, origin.donor_seed, origin.operations
            ));
        }
        let uses_map = items.contains("HashMap") || body.contains("HashMap");
        let uses_set = items.contains("HashSet") || body.contains("HashSet");
        match (uses_map, uses_set) {
            (true, true) => source.push_str("use std::collections::{HashMap, HashSet};\n\n"),
            (true, false) => source.push_str("use std::collections::HashMap;\n\n"),
            (false, true) => source.push_str("use std::collections::HashSet;\n\n"),
            (false, false) => {}
        }
        source.push_str(&items);
        source.push_str("fn main() {\n");
        source.push_str(&body);
        source.push_str("}\n");
        source
    }

    /// The coverage features every block contributes, for the generator
    /// tests and the campaign gap report.
    pub fn structural_features(&self) -> BTreeSet<&'static str> {
        let mut out = BTreeSet::new();
        for block in &self.blocks {
            block.features(&mut out);
        }
        out
    }

    /// A compact shape string, so a campaign can count distinct topologies.
    pub fn structural_signature(&self) -> String {
        let mut out = String::new();
        for block in &self.blocks {
            block.shape(&mut out);
        }
        out
    }

    /// Smaller programs that may reproduce the same failure, tried in order
    /// by the reducer.
    pub fn shrink_candidates(&self) -> Vec<Program> {
        let mut out = Vec::new();
        if self.blocks.len() > 1 {
            for index in 0..self.blocks.len() {
                let mut candidate = self.clone();
                candidate.blocks.remove(index);
                out.push(candidate);
            }
        }
        for index in 0..self.blocks.len() {
            for block in self.blocks[index].shrinks() {
                let mut candidate = self.clone();
                candidate.blocks[index] = block;
                out.push(candidate);
            }
        }
        out
    }
}
